"""Autonomous self-coding scheduler and planner tests."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import yaml


def _spec_dict(
    *,
    slug: str,
    status: str = "pending_approval",
    tier: int = 1,
    live_env_activation: bool = False,
    approved_by: str | None = None,
) -> dict[str, Any]:
    spec: dict[str, Any] = {
        "slug": slug,
        "title": f"Spec {slug}",
        "created_at": "2026-05-12T10:00:00+00:00",
        "created_by": "zhvusha",
        "tier": tier,
        "goal": "Добавить безопасное автономное улучшение Жвушиного самокодинга.",
        "failing_test": {
            "file": "tests/skills/autonomous_self_coding/test_skill.py",
            "name": "test_generated_spec_can_be_self_approved_and_started",
            "spec": "Autonomous cycle approves low-risk spec and starts implementation.",
        },
        "whitelist_paths": [
            "src/skills/autonomous_self_coding/skill.py",
            "tests/skills/autonomous_self_coding/test_skill.py",
        ],
        "blast_radius": ["new autonomous self-coding orchestration only"],
        "rollback_path": ["git revert"],
        "preserve_behavior": [
            "Existing /код, specs, gates, archive and manual approval flow stay intact.",
        ],
        "allowed_simplifications": [],
        "rationale": "Generated by Жвуша from self-work context.",
        "source_provenance": [
            {
                "url": "workspace:self-work",
                "source_type": "local_repo",
                "trust_tier": "direct",
                "claim": "Self-work context selected this low-risk improvement.",
            }
        ],
        "status": status,
        "live_env_activation": live_env_activation,
    }
    if live_env_activation:
        spec["live_env_keys"] = ["SAFE_OPTION"]
    if approved_by is not None:
        spec["approved_by"] = approved_by
        spec["approved_at"] = "2026-05-12T10:05:00+00:00"
        if approved_by == "zhvusha":
            spec["autonomous_approval_reason"] = "Existing safe autonomous spec."
    return spec


def _write_spec(tasks_dir: Path, spec: dict[str, Any]) -> Path:
    tasks_dir.mkdir(parents=True, exist_ok=True)
    path = tasks_dir / f"2026-05-12-{spec['slug']}.yaml"
    path.write_text(yaml.safe_dump(spec, allow_unicode=True, sort_keys=False))
    return path


def _workspace(root: Path) -> Path:
    workspace = root / "workspace"
    (workspace / "personality").mkdir(parents=True)
    (workspace / "personality" / "pillars.md").write_text(
        "# Столпы\n- Качественное усложнение\n", encoding="utf-8"
    )
    (workspace / "inbox").mkdir()
    (workspace / "inbox" / "consolidation_results.md").write_text(
        "Новая идея: улучшить автономный кодинг без упрощения личности.",
        encoding="utf-8",
    )
    archive = workspace / "self_coding_archive" / "prev-cycle"
    archive.mkdir(parents=True)
    (archive / "summary.md").write_text(
        "Урок: всегда сохранять whitelist/test gates.",
        encoding="utf-8",
    )
    return workspace


def _job() -> Any:
    from src.agent_runtime.models import AgentJob, ContextPack, InvocationProfile

    return AgentJob.new(
        owner_user_id=123,
        chat_id=123,
        source_message_id="cycle:1",
        fingerprint="fp",
        kind="self_improvement",
        profile=InvocationProfile(id="self_improvement.autonomous"),
        context_pack=ContextPack(user_request="autonomous cycle"),
    )


class FakeIdeationSkill:
    def __init__(self, tasks_dir: Path, *, tier: int = 1) -> None:
        self.tasks_dir = tasks_dir
        self.tier = tier
        self.calls: list[tuple[str, Any]] = []

    async def execute(self, message: str, context: Any) -> Any:
        from src.skills.base import SkillResult

        self.calls.append((message, context))
        slug = "generated-safe-spec"
        _write_spec(self.tasks_dir, _spec_dict(slug=slug, tier=self.tier))
        return SkillResult(
            success=True,
            response="Spec generated.",
            metadata={"slug": slug, "tier": self.tier},
        )


class FakeImplementationRunner:
    def __init__(self) -> None:
        self.calls: list[tuple[str, Any, tuple[str, ...]]] = []
        self.callbacks: list[Any] = []

    async def start_background(
        self,
        *,
        slug: str,
        context: Any,
        recent_messages: tuple[str, ...] = (),
        completion_callback: Any,
    ) -> Any:
        self.calls.append((slug, context, recent_messages))
        self.callbacks.append(completion_callback)
        return SimpleNamespace(id=f"job-impl-{slug}")


async def test_generated_spec_can_be_self_approved_and_started(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    workspace = _workspace(tmp_path)
    ideation = FakeIdeationSkill(tasks_dir)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=workspace,
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
        clock=lambda: datetime(2026, 5, 12, 10, 15, tzinfo=UTC),
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)

    spec = yaml.safe_load(
        (tasks_dir / "2026-05-12-generated-safe-spec.yaml").read_text(encoding="utf-8")
    )
    assert result.status == "started_implementation"
    assert result.spec_slug == "generated-safe-spec"
    assert spec["status"] == "approved"
    assert spec["approved_by"] == "zhvusha"
    assert "Tier 1" in spec["autonomous_approval_reason"]
    assert implementation.calls[0][0] == "generated-safe-spec"
    assert "Качественное усложнение" in ideation.calls[0][0]
    assert "whitelist/test gates" in ideation.calls[0][0]


async def test_planner_prefers_context_pack_self_work_capsule(
    tmp_path: Path,
) -> None:
    from src.agent_runtime.models import AgentJob, ContextPack, InvocationProfile
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    workspace = _workspace(tmp_path)
    ideation = FakeIdeationSkill(tasks_dir)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=workspace,
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
    )
    context_pack = ContextPack(
        user_request="autonomous cycle",
        active_code_state=(
            "## Self-work Context Capsule\n"
            "- Capability gap: agent_profile.telegram_mcp.personal_readonly\n"
            "- safe_spec_candidate:agent_profile.telegram_mcp.personal_readonly"
        ),
        chat_context=("recent failed run: tests/runtime/test_gap.py::test_gap",),
        metadata={"self_work_context_capsule": "true"},
    )
    job = AgentJob.new(
        owner_user_id=123,
        chat_id=123,
        source_message_id="cycle:1",
        fingerprint="fp",
        kind="self_improvement",
        profile=InvocationProfile(id="self_improvement.autonomous"),
        context_pack=context_pack,
    )

    result = await engine.run_once(job=job, context_pack=context_pack)

    assert result.status == "started_implementation"
    request = ideation.calls[0][0]
    assert "agent_profile.telegram_mcp.personal_readonly" in request
    assert "tests/runtime/test_gap.py::test_gap" in request
    assert "Качественное усложнение" not in request


async def test_existing_approved_spec_requires_fresh_confirmation(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    _write_spec(
        tasks_dir,
        _spec_dict(
            slug="already-approved",
            status="approved",
            tier=1,
            approved_by="zhvusha",
        ),
    )
    ideation = FakeIdeationSkill(tasks_dir)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)

    assert result.status == "blocked"
    assert result.spec_slug == "already-approved"
    assert "свежее подтверждение Никиты" in result.summary
    assert "актуальна ли `already-approved`" in " ".join(result.next_actions)
    assert ideation.calls == []
    assert implementation.calls == []


async def test_existing_pending_spec_requires_fresh_confirmation_before_approval(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    _write_spec(tasks_dir, _spec_dict(slug="old-pending-spec"))
    ideation = FakeIdeationSkill(tasks_dir)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)
    spec = yaml.safe_load(
        (tasks_dir / "2026-05-12-old-pending-spec.yaml").read_text(encoding="utf-8")
    )

    assert result.status == "blocked"
    assert result.spec_slug == "old-pending-spec"
    assert "свежее подтверждение Никиты" in result.summary
    assert spec["status"] == "pending_approval"
    assert ideation.calls == []
    assert implementation.calls == []


async def test_generated_spec_above_autonomous_tier_stays_pending(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    ideation = FakeIdeationSkill(tasks_dir, tier=2)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)
    spec = yaml.safe_load(
        (tasks_dir / "2026-05-12-generated-safe-spec.yaml").read_text(encoding="utf-8")
    )

    assert result.status == "created_pending"
    assert "Tier 2" in result.summary
    assert spec["status"] == "pending_approval"
    assert implementation.calls == []


async def test_generated_tier3_spec_requires_nikita_chat_approval(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    ideation = FakeIdeationSkill(tasks_dir, tier=3)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=3,
        clock=lambda: datetime(2026, 5, 12, 10, 15, tzinfo=UTC),
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)
    spec = yaml.safe_load(
        (tasks_dir / "2026-05-12-generated-safe-spec.yaml").read_text(encoding="utf-8")
    )

    assert result.status == "created_pending"
    assert result.spec_slug == "generated-safe-spec"
    assert "Tier 3" in result.summary
    assert "Никита" in result.summary
    assert "Разрешаешь запуск" in " ".join(result.next_actions)
    assert "full spec" in " ".join(result.next_actions)
    assert "AI approval classifier" in " ".join(result.next_actions)
    assert spec["status"] == "pending_approval"
    assert implementation.calls == []


async def test_existing_tier3_spec_still_requires_fresh_confirmation(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    _write_spec(
        tasks_dir,
        _spec_dict(
            slug="nikita-approved-tier3",
            status="approved",
            tier=3,
            approved_by="nikita",
        ),
    )
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=FakeIdeationSkill(tasks_dir, tier=1),
        implementation_runner=implementation,
        max_autonomous_tier=3,
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)

    assert result.status == "blocked"
    assert result.spec_slug == "nikita-approved-tier3"
    assert "свежее подтверждение Никиты" in result.summary
    assert implementation.calls == []


async def test_autonomous_cycle_writes_detailed_change_summary_on_completion(
    tmp_path: Path,
) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine
    from src.skills.base import SkillResult

    tasks_dir = tmp_path / "tasks"
    workspace = _workspace(tmp_path)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=workspace,
        admin_user_id=123,
        ideation_skill=FakeIdeationSkill(tasks_dir, tier=1),
        implementation_runner=implementation,
        max_autonomous_tier=3,
        clock=lambda: datetime(2026, 5, 12, 10, 15, tzinfo=UTC),
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)
    await implementation.callbacks[0](
        SkillResult(
            success=True,
            response="Готово: `main` @ `abc123`. Изменены runtime gates.",
            metadata={
                "branch": "main",
                "commit_sha": "abc123",
                "spec_path": "tasks/2026-05-12-generated-safe-spec.yaml",
            },
        )
    )

    assert result.change_summary_path
    summary_path = Path(result.change_summary_path)
    assert summary_path.exists()
    summary = summary_path.read_text(encoding="utf-8")
    assert "# Сводка автономного изменения" in summary
    assert "generated-safe-spec" in summary
    assert "Tier 1" in summary
    assert "commit_sha: abc123" in summary
    assert "src/skills/autonomous_self_coding/skill.py" in summary
    assert "Existing /код, specs, gates" in summary


async def test_pending_live_env_spec_is_not_self_approved(tmp_path: Path) -> None:
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine

    tasks_dir = tmp_path / "tasks"
    _write_spec(
        tasks_dir,
        _spec_dict(
            slug="needs-env",
            status="pending_approval",
            tier=1,
            live_env_activation=True,
        ),
    )
    ideation = FakeIdeationSkill(tasks_dir)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
    )

    result = await engine.run_once(job=_job(), context_pack=_job().context_pack)

    assert result.status == "blocked"
    assert "live env" in result.summary.lower()
    assert implementation.calls == []


async def test_background_skill_creates_durable_self_improvement_job() -> None:
    from src.agent_runtime.events import InMemoryAgentEventStream
    from src.agent_runtime.models import ContextCapsule
    from src.agent_runtime.profiles import SELF_IMPROVEMENT_AUTONOMOUS
    from src.agent_runtime.runtime import AgentRuntime
    from src.agent_runtime.storage import InMemoryAgentJobStore
    from src.skills.autonomous_self_coding.skill import AutonomousSelfCodingSkill

    class Worker:
        name = "self_improvement"

        async def run(self, *, job: Any, context_pack: Any) -> ContextCapsule:
            del context_pack
            return ContextCapsule(
                summary="cycle done",
                artifacts=(f"job:{job.id}",),
            )

        async def cancel(self, job_id: str) -> bool:
            del job_id
            return False

    runtime = AgentRuntime(
        store=InMemoryAgentJobStore(),
        events=InMemoryAgentEventStream(),
        workers={"self_improvement": Worker()},
    )
    skill = AutonomousSelfCodingSkill(
        admin_user_id=123,
        runtime=runtime,
        profile=SELF_IMPROVEMENT_AUTONOMOUS,
        clock=lambda: datetime(2026, 5, 12, 10, 0, tzinfo=UTC),
    )

    result = await skill.run_once(cycle_id="cycle-fixed")

    assert result.success
    assert result.metadata["agent_job_id"].startswith("job-")
    job = await runtime.status(result.metadata["agent_job_id"])
    assert job.kind == "self_improvement"
    assert job.profile.id == "self_improvement.autonomous"
    assert job.context_pack.constraints


async def test_background_skill_injects_self_work_context_capsule() -> None:
    from src.agent_runtime.events import InMemoryAgentEventStream
    from src.agent_runtime.models import ContextCapsule
    from src.agent_runtime.profiles import SELF_IMPROVEMENT_AUTONOMOUS
    from src.agent_runtime.runtime import AgentRuntime
    from src.agent_runtime.storage import InMemoryAgentJobStore
    from src.skills.autonomous_self_coding.skill import AutonomousSelfCodingSkill

    class Worker:
        name = "self_improvement"

        async def run(self, *, job: Any, context_pack: Any) -> ContextCapsule:
            del context_pack
            return ContextCapsule(summary="cycle done", artifacts=(f"job:{job.id}",))

        async def cancel(self, job_id: str) -> bool:
            del job_id
            return False

    class SelfWorkContextProvider:
        async def build_self_work_context_capsule(self) -> ContextCapsule:
            return ContextCapsule(
                summary="Self-work capsule ready.",
                processed_context=(
                    "Capability gap: agent_profile.telegram_mcp.personal_readonly"
                ),
                next_actions=(
                    "Create bounded spec candidate for "
                    "agent_profile.telegram_mcp.personal_readonly.",
                ),
                artifacts=(
                    "safe_spec_candidate:agent_profile.telegram_mcp.personal_readonly",
                ),
                markdown_report=(
                    "## Self-work Context Capsule\n"
                    "- Capability gap: agent_profile.telegram_mcp.personal_readonly"
                ),
            )

    runtime = AgentRuntime(
        store=InMemoryAgentJobStore(),
        events=InMemoryAgentEventStream(),
        workers={"self_improvement": Worker()},
    )
    skill = AutonomousSelfCodingSkill(
        admin_user_id=123,
        runtime=runtime,
        profile=SELF_IMPROVEMENT_AUTONOMOUS,
        self_work_context_provider=SelfWorkContextProvider(),
        clock=lambda: datetime(2026, 5, 12, 10, 0, tzinfo=UTC),
    )

    result = await skill.run_once(cycle_id="cycle-fixed")

    assert result.success
    job = await runtime.status(result.metadata["agent_job_id"])
    assert job.context_pack.metadata["self_work_context_capsule"] == "true"
    assert "agent_profile.telegram_mcp.personal_readonly" in (
        job.context_pack.active_code_state
    )
    assert "Self-work capsule ready." in job.context_pack.chat_context
    assert (
        job.context_pack.metadata["self_work_safe_spec_candidates"]
        == "agent_profile.telegram_mcp.personal_readonly"
    )


async def test_runtime_gap_context_reaches_planner_as_structured_candidate(
    tmp_path: Path,
) -> None:
    from src.agent_runtime.events import InMemoryAgentEventStream
    from src.agent_runtime.models import ContextCapsule
    from src.agent_runtime.profiles import SELF_IMPROVEMENT_AUTONOMOUS
    from src.agent_runtime.runtime import AgentRuntime
    from src.agent_runtime.storage import InMemoryAgentJobStore
    from src.agent_runtime.workers.self_improvement import (
        AutonomousSelfCodingWorkerBackend,
    )
    from src.skills.autonomous_self_coding.planner import AutonomousSelfCodingEngine
    from src.skills.autonomous_self_coding.skill import AutonomousSelfCodingSkill

    class SelfWorkContextProvider:
        async def build_self_work_context_capsule(self) -> ContextCapsule:
            return ContextCapsule(
                summary="Runtime gap capsule ready.",
                processed_context=(
                    "## Capability gaps\n"
                    "- agent_profile.telegram_mcp.personal_readonly: degraded - "
                    "session=super_secret_session"
                ),
                next_actions=(
                    "Create bounded spec candidate for "
                    "agent_profile.telegram_mcp.personal_readonly.",
                ),
                artifacts=(
                    "safe_spec_candidate:agent_profile.telegram_mcp.personal_readonly",
                ),
                markdown_report=(
                    "## Self-work Context Capsule\n"
                    "- Capability gap: agent_profile.telegram_mcp.personal_readonly"
                ),
            )

    tasks_dir = tmp_path / "tasks"
    ideation = FakeIdeationSkill(tasks_dir)
    implementation = FakeImplementationRunner()
    engine = AutonomousSelfCodingEngine(
        tasks_dir=tasks_dir,
        workspace_root=_workspace(tmp_path),
        admin_user_id=123,
        ideation_skill=ideation,
        implementation_runner=implementation,
        max_autonomous_tier=1,
        clock=lambda: datetime(2026, 5, 12, 10, 15, tzinfo=UTC),
    )
    runtime = AgentRuntime(
        store=InMemoryAgentJobStore(),
        events=InMemoryAgentEventStream(),
        workers={"self_improvement": AutonomousSelfCodingWorkerBackend(engine=engine)},
    )
    skill = AutonomousSelfCodingSkill(
        admin_user_id=123,
        runtime=runtime,
        profile=SELF_IMPROVEMENT_AUTONOMOUS,
        self_work_context_provider=SelfWorkContextProvider(),
        clock=lambda: datetime(2026, 5, 12, 10, 0, tzinfo=UTC),
    )

    result = await skill.run_once(cycle_id="cycle-runtime-gap")
    completed = await runtime.wait_background(result.metadata["agent_job_id"])

    spec = yaml.safe_load(
        (tasks_dir / "2026-05-12-generated-safe-spec.yaml").read_text(encoding="utf-8")
    )
    request = ideation.calls[0][0]
    assert completed is not None
    assert completed.status.value == "done"
    assert "Structured self-work candidates" in request
    assert (
        "safe_spec_candidate: agent_profile.telegram_mcp.personal_readonly" in request
    )
    assert "super_secret_session" not in request
    assert spec["status"] == "approved"
    assert implementation.calls[0][0] == "generated-safe-spec"
