"""Behaviour tests for SpecCommandSkill — list/show/approve/reject + intent.

Uses tmp_path-based tasks/ directory, dummy ``Bot`` mock, and an injected
intent-classifier callable so the skill can stay LLM-free in tests
(per AGENTS.md rule 0 — only Haiku in tests, and these contract-level
tests use no LLM at all).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock

import pytest
import yaml

pytestmark = pytest.mark.contract


def _spec_dict(
    *,
    slug: str = "weather-skill",
    status: str = "pending_approval",
    tier: int = 1,
    title: str = "Add weather skill",
) -> dict[str, Any]:
    return {
        "slug": slug,
        "title": title,
        "created_at": "2026-04-26T12:00:00+00:00",
        "created_by": "zhvusha",
        "tier": tier,
        "goal": "Дать Жвуше команду /weather, возвращающую температуру по городу.",
        "failing_test": {
            "file": f"tests/skills/{slug}/test_contract.py",
            "name": "test_returns_temp",
            "spec": "Mock API → response contains '12.5'.",
        },
        "whitelist_paths": [
            f"src/skills/{slug}/__init__.py",
            f"src/skills/{slug}/skill.py",
        ],
        "blast_radius": ["new skill, no existing skill touched"],
        "rollback_path": ["git revert", f"rm -rf src/skills/{slug}/"],
        "preserve_behavior": [
            "Existing skills, fallbacks, tests and chat behaviour stay intact.",
        ],
        "allowed_simplifications": [],
        "rationale": "Spec is generated by Жвуша and needs archive evidence.",
        "source_provenance": [
            {
                "url": "local:test",
                "source_type": "local_repo",
                "trust_tier": "direct",
                "claim": "Test helper generated this spec.",
            }
        ],
        "status": status,
    }


def _write_spec(tasks_dir: Path, spec: dict[str, Any]) -> Path:
    tasks_dir.mkdir(parents=True, exist_ok=True)
    path = tasks_dir / f"2026-04-26-{spec['slug']}.yaml"
    path.write_text(yaml.safe_dump(spec, allow_unicode=True, sort_keys=False))
    return path


def _make_skill(tasks_dir: Path, *, admin_user_id: int = 12345) -> Any:
    from src.skills.spec_command.skill import SpecCommandSkill

    return SpecCommandSkill(
        tasks_dir=tasks_dir,
        admin_user_id=admin_user_id,
        intent_classifier=None,  # keyword-only fallback for these tests
    )


def _ctx(
    *,
    user_id: int = 12345,
    mode: str = "personal",
    bot: Any = None,
    metadata: dict[str, Any] | None = None,
) -> Any:
    from src.skills.base import AgentContext

    return AgentContext(
        user_id=user_id,
        chat_id=user_id,
        mode=mode,  # type: ignore[arg-type]
        bot=bot,
        metadata=metadata or {},
    )


class TestCanHandle:
    async def test_admin_with_spec_prefix_full_match(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        confidence = await skill.can_handle("/spec list", _ctx())
        assert confidence >= 0.9

    async def test_non_admin_returns_zero(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        confidence = await skill.can_handle("/spec list", _ctx(user_id=99))
        assert confidence == 0.0

    async def test_assistant_mode_returns_zero(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        confidence = await skill.can_handle("/spec list", _ctx(mode="assistant"))
        assert confidence == 0.0

    async def test_unrelated_text_returns_zero(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        skill = _make_skill(tasks_dir)
        confidence = await skill.can_handle("привет, как дела", _ctx())
        assert confidence == 0.0

    async def test_natural_spec_commands_route_high_confidence(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(status="pending_approval"))
        skill = _make_skill(tasks_dir)

        assert await skill.can_handle("покажи spec weather-skill", _ctx()) >= 0.9
        assert await skill.can_handle("одобри spec weather-skill", _ctx()) >= 0.9
        assert await skill.can_handle("отклони spec weather-skill", _ctx()) >= 0.9
        assert await skill.can_handle("обсудим spec weather-skill", _ctx()) == 0.0

    async def test_natural_approve_with_pending_spec_returns_high(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(status="pending_approval"))
        skill = _make_skill(tasks_dir)
        confidence = await skill.can_handle("одобряю", _ctx())
        assert confidence >= 0.6

    async def test_natural_approve_without_pending_spec_returns_zero(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        skill = _make_skill(tasks_dir)
        confidence = await skill.can_handle("одобряю", _ctx())
        assert confidence == 0.0

    async def test_tier3_natural_approve_requires_ai_classifier(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(status="pending_approval", tier=3))
        skill = _make_skill(tasks_dir)

        confidence = await skill.can_handle("одобряю", _ctx())

        assert confidence == 0.0

    async def test_tier3_irrelevant_text_with_classifier_returns_zero(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.IRRELEVANT)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        confidence = await skill.can_handle("Але", _ctx())

        assert confidence == 0.0
        classifier.assert_awaited_once_with("Але", "architecture-change")

    async def test_tier3_clarify_text_with_classifier_does_not_shadow_chat(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.CLARIFY)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        confidence = await skill.can_handle("Не понял", _ctx())

        assert confidence == 0.0
        classifier.assert_awaited_once_with("Не понял", "architecture-change")

    async def test_tier3_can_handle_caches_classifier_intent_for_execute(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.APPROVE)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        confidence = await skill.can_handle("одобряю", _ctx())
        result = await skill.execute("одобряю", _ctx())

        assert confidence >= 0.8
        assert result.success
        classifier.assert_awaited_once_with("одобряю", "architecture-change")
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"

    async def test_codex_goal_loop_proof_replay_is_not_spec_approval(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.APPROVE)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )
        proof_replay = """
        Codex/operator proof replay, sender=codex, не Никита.
        Это продолжение active goal loop, не новое сообщение пользователя.
        No-Write Proof Bundle:
        - status=complete
        Decision request:
        Выбери approve_exact_implementation или blocked_by_dirty_target_or_missing_capability.
        """

        confidence = await skill.can_handle(
            proof_replay,
            _ctx(
                metadata={
                    "source": "vscode",
                    "interface": "vscode",
                    "source_actor": "codex",
                    "operator_message_kind": "goal_loop_proof_replay",
                }
            ),
        )

        assert confidence == 0.0
        classifier.assert_not_called()


class TestCanHandleDoesNotShadowSiblings:
    """SpecCommand owns ``/spec`` and ``/spec <subcommand>`` — must NOT match
    sibling triggers like ``/spec_run`` (Editor) or ``/spec_create`` (Architect).

    Otherwise dispatcher returns the SpecCommand help instead of routing the
    Telegram message to the right skill (regression observed 2026-04-26).
    """

    async def test_spec_run_returns_zero(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        confidence = await skill.can_handle("/spec_run weather-skill", _ctx())
        assert confidence == 0.0

    async def test_spec_create_returns_zero(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        confidence = await skill.can_handle("/spec_create new feature", _ctx())
        assert confidence == 0.0

    async def test_bare_spec_still_matches(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        confidence = await skill.can_handle("/spec", _ctx())
        assert confidence >= 0.9

    async def test_spec_subcommands_still_match(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        for cmd in (
            "/spec list",
            "/spec show foo",
            "/spec approve foo",
            "/spec reject foo bar",
        ):
            confidence = await skill.can_handle(cmd, _ctx())
            assert confidence >= 0.9, f"failed for {cmd!r}: got {confidence}"

    async def test_execute_unknown_subcommand_returns_help(
        self, tmp_path: Path
    ) -> None:
        """Defence-in-depth: even if can_handle let through, execute must
        not echo HELP for ``/spec_run`` (which would mask the routing bug)."""
        skill = _make_skill(tmp_path / "tasks")
        result = await skill.execute("/spec_run weather-skill", _ctx())
        # Either no response (let other skills take over) or a friendly
        # "unknown" message — but NOT the full SpecCommand help text.
        assert "/spec list" not in result.response or not result.success


class TestListCommand:
    async def test_list_empty_tasks_dir(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        skill = _make_skill(tasks_dir)

        result = await skill.execute("/spec list", _ctx())

        assert result.success
        assert "нет" in result.response.lower() or "empty" in result.response.lower()

    async def test_list_includes_pending_specs(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(slug="alpha", status="pending_approval"))
        _write_spec(tasks_dir, _spec_dict(slug="bravo", status="approved"))
        _write_spec(tasks_dir, _spec_dict(slug="charlie", status="done"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec list", _ctx())

        assert result.success
        # Default filter: not done/rejected/failed.
        assert "alpha" in result.response
        assert "bravo" in result.response
        assert "charlie" not in result.response

    async def test_list_groups_by_status(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(slug="alpha", status="pending_approval"))
        _write_spec(tasks_dir, _spec_dict(slug="bravo", status="approved"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec list", _ctx())

        assert "pending" in result.response.lower()
        assert "approved" in result.response.lower()


class TestShowCommand:
    async def test_show_renders_spec_fields(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec show weather-skill", _ctx())

        assert result.success
        assert "weather-skill" in result.response
        assert "tier" in result.response.lower()
        assert "Add weather skill" in result.response  # title
        assert "Preserve behavior" in result.response
        assert "Allowed simplifications" in result.response
        assert "Chat context" in result.response

    async def test_show_renders_chat_context(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        spec = _spec_dict(slug="weather-skill")
        spec["chat_context"] = [
            "Никита: сначала обсудили приветствие",
            "Жвуша: сохраняем живость без театра.",
        ]
        _write_spec(tasks_dir, spec)

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec show weather-skill", _ctx())

        assert "сначала обсудили приветствие" in result.response
        assert "сохраняем живость" in result.response

    async def test_natural_show_renders_spec_fields(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("покажи spec weather-skill", _ctx())

        assert result.success
        assert "weather-skill" in result.response
        assert "Add weather skill" in result.response

    async def test_natural_show_tolerates_extra_spacing(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("покажи   spec: weather-skill", _ctx())

        assert result.success
        assert "weather-skill" in result.response

    async def test_show_unknown_slug_returns_helpful_error(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec show nonexistent", _ctx())

        assert (
            "не найден" in result.response.lower()
            or "not found" in result.response.lower()
        )

    async def test_show_without_slug_returns_help(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        result = await skill.execute("/spec show", _ctx())

        assert "slug" in result.response.lower() or "укажи" in result.response.lower()


class TestApproveCommand:
    async def test_approve_changes_status_to_approved(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec approve weather-skill", _ctx())

        assert result.success
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"
        assert reloaded["approved_by"] == "nikita"
        assert "approved_at" in reloaded
        # Parseable as ISO datetime.
        datetime.fromisoformat(reloaded["approved_at"])

    async def test_natural_approve_command_changes_status_to_approved(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("одобри spec weather-skill", _ctx())

        assert result.success
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"
        assert reloaded["approved_by"] == "nikita"

    async def test_approve_already_approved_returns_message(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(slug="weather-skill", status="approved"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec approve weather-skill", _ctx())

        assert "уже" in result.response.lower() or "already" in result.response.lower()

    async def test_approve_failed_spec_reopens_for_retry(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        spec = _spec_dict(slug="weather-skill", status="failed")
        spec["branch"] = "isolated:weather-skill:123:1"
        spec["commit_sha"] = "deadbeef"
        spec["failed_attempts"] = ["Commit gate failed."]
        path = _write_spec(tasks_dir, spec)

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec approve weather-skill", _ctx())

        assert result.success
        assert "повторной попытки" in result.response
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"
        assert reloaded["approved_by"] == "nikita"
        assert "approved_at" in reloaded
        datetime.fromisoformat(reloaded["approved_at"])
        assert reloaded["failed_attempts"] == ["Commit gate failed."]
        assert reloaded["branch"] is None
        assert reloaded["commit_sha"] is None

    async def test_approve_unknown_slug(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        result = await skill.execute("/spec approve missing", _ctx())

        assert (
            "не найден" in result.response.lower()
            or "not found" in result.response.lower()
        )

    async def test_natural_approve_text_routes_to_pending_spec(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(
            tasks_dir, _spec_dict(slug="alpha", status="pending_approval")
        )

        skill = _make_skill(tasks_dir)
        result = await skill.execute("одобряю", _ctx())

        assert result.success
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"

    async def test_natural_approve_picks_most_recent_pending(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        # Write older first so file mtime is older.
        path_old = _write_spec(
            tasks_dir, _spec_dict(slug="alpha", status="pending_approval")
        )
        # Newer file (later mtime by virtue of being written second).
        path_new = _write_spec(
            tasks_dir, _spec_dict(slug="bravo", status="pending_approval")
        )

        skill = _make_skill(tasks_dir)
        result = await skill.execute("давай", _ctx())

        assert result.success
        # bravo should be approved, alpha untouched.
        bravo = yaml.safe_load(path_new.read_text())
        alpha = yaml.safe_load(path_old.read_text())
        assert bravo["status"] == "approved"
        assert alpha["status"] == "pending_approval"

    async def test_tier3_natural_approve_uses_classifier_even_for_keyword(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.APPROVE)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )
        result = await skill.execute("одобряю", _ctx())

        assert result.success
        classifier.assert_awaited_once_with("одобряю", "architecture-change")
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"

    async def test_tier3_explicit_natural_approve_uses_classifier(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.APPROVE)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        confidence = await skill.can_handle("одобри spec architecture-change", _ctx())
        result = await skill.execute("одобри spec architecture-change", _ctx())

        assert confidence >= 0.9
        assert result.success
        classifier.assert_awaited_once_with(
            "одобри spec architecture-change", "architecture-change"
        )
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"

    async def test_tier3_explicit_natural_approve_without_classifier_does_not_approve(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        skill = _make_skill(tasks_dir)
        result = await skill.execute("одобри spec architecture-change", _ctx())

        assert result.success
        assert "AI-классификации" in result.response
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "pending_approval"

    async def test_tier3_natural_approve_without_classifier_does_not_approve(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        skill = _make_skill(tasks_dir)
        result = await skill.execute("одобряю", _ctx())

        assert result.success
        assert "AI-классификации" in result.response
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "pending_approval"


async def test_spec_approve_bundle_records_scope_for_multiple_specs(
    tmp_git_repo: Path,
) -> None:
    from src.skills.spec_command.skill import SpecCommandSkill

    tasks_dir = tmp_git_repo / "tasks"
    alpha_path = _write_spec(
        tasks_dir,
        _spec_dict(
            slug="alpha-architecture",
            status="pending_approval",
            tier=3,
            title="Alpha architecture change",
        ),
    )
    bravo_spec = _spec_dict(
        slug="bravo-safety",
        status="pending_approval",
        tier=3,
        title="Bravo safety change",
    )
    bravo_spec["chat_context"] = ["Никита: это уже обсуждали как один пакет."]
    bravo_path = _write_spec(tasks_dir, bravo_spec)
    subprocess_run_git(tmp_git_repo, "add", "-A")
    subprocess_run_git(tmp_git_repo, "commit", "-m", "init pending specs")
    head_before = _git_stdout(tmp_git_repo, "rev-parse", "HEAD").strip()

    skill = SpecCommandSkill(
        tasks_dir=tasks_dir,
        admin_user_id=12345,
        intent_classifier=None,
        repo_root=tmp_git_repo,
    )

    result = await skill.execute(
        "/spec approve-bundle alpha-architecture bravo-safety "
        '--scope "Tier 3 self-coding approval packet" '
        '--reason "avoid micro-approval stalls while keeping destructive actions separate"',
        _ctx(),
    )

    assert result.success
    assert _git_stdout(tmp_git_repo, "rev-parse", "HEAD").strip() == head_before
    assert "approved" in result.response
    assert "spec_run" in result.response

    for path in (alpha_path, bravo_path):
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"
        assert reloaded["approved_by"] == "nikita"
        datetime.fromisoformat(reloaded["approved_at"])
        audit_lines = [
            line
            for line in reloaded["chat_context"]
            if "approve-bundle" in line and "Tier 3 self-coding approval packet" in line
        ]
        assert audit_lines
        audit_line = audit_lines[-1]
        assert "alpha-architecture" in audit_line
        assert "bravo-safety" in audit_line
        assert "avoid micro-approval stalls" in audit_line
        assert "/spec_run" in audit_line
        assert "commit" in audit_line
        assert "restart" in audit_line
        assert ".env" in audit_line
        assert "private-source read" in audit_line


async def test_spec_approve_bundle_requires_reason_without_mutation(
    tmp_path: Path,
) -> None:
    tasks_dir = tmp_path / "tasks"
    alpha_path = _write_spec(
        tasks_dir, _spec_dict(slug="alpha", status="pending_approval", tier=3)
    )
    bravo_path = _write_spec(
        tasks_dir, _spec_dict(slug="bravo", status="pending_approval", tier=3)
    )
    skill = _make_skill(tasks_dir)

    result = await skill.execute(
        '/spec approve-bundle alpha bravo --scope "shared Tier 3 approval"',
        _ctx(),
    )

    assert result.success
    assert "reason" in result.response
    for path in (alpha_path, bravo_path):
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "pending_approval"
        assert "approved_by" not in reloaded
        assert "chat_context" not in reloaded


async def test_spec_approve_bundle_preflights_all_statuses_before_mutation(
    tmp_path: Path,
) -> None:
    tasks_dir = tmp_path / "tasks"
    alpha_path = _write_spec(
        tasks_dir, _spec_dict(slug="alpha", status="pending_approval", tier=3)
    )
    bravo_path = _write_spec(tasks_dir, _spec_dict(slug="bravo", status="approved"))
    skill = _make_skill(tasks_dir)

    result = await skill.execute(
        "/spec approve-bundle alpha bravo "
        '--scope "shared Tier 3 approval" '
        '--reason "approve related changes together"',
        _ctx(),
    )

    assert result.success
    assert "pending_approval" in result.response
    alpha = yaml.safe_load(alpha_path.read_text())
    bravo = yaml.safe_load(bravo_path.read_text())
    assert alpha["status"] == "pending_approval"
    assert "approved_by" not in alpha
    assert bravo["status"] == "approved"


class TestRejectCommand:
    async def test_reject_changes_status_to_rejected(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec reject weather-skill out of scope", _ctx())

        assert result.success
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "rejected"
        assert reloaded["rejected_reason"] == "out of scope"

    async def test_reject_without_reason(self, tmp_path: Path) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)
        result = await skill.execute("/spec reject weather-skill", _ctx())

        assert result.success
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "rejected"
        assert reloaded["rejected_reason"] is None or reloaded["rejected_reason"] == ""


def _git_stdout(repo: Path, *args: str) -> str:
    import subprocess

    return subprocess.run(  # noqa: S603 — args literal
        ["git", *args],  # noqa: S607 — git on PATH
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    ).stdout


class TestApproveAutoCommitsYaml:
    """Phase 19 — when ``repo_root`` is supplied, ``/spec approve`` must
    auto-commit the yaml mutation so the next ``/spec_run`` starts on a
    clean worktree.

    Pre-Phase-19, every approve produced a modified-but-uncommitted
    yaml; ``BranchManager._assert_clean_tree`` then refused
    ``/spec_run``, forcing operators to land the mutation manually.
    """

    async def test_approve_lands_yaml_commit(self, tmp_git_repo: Path) -> None:
        """After approve, the yaml mutation lives in HEAD, not in the
        worktree."""
        from src.skills.spec_command.skill import SpecCommandSkill

        tasks_dir = tmp_git_repo / "tasks"
        spec_path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))
        # Land the initial spec under HEAD so we have a clean baseline.
        subprocess_run_git(tmp_git_repo, "add", "-A")
        subprocess_run_git(tmp_git_repo, "commit", "-m", "init spec")

        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=None,
            repo_root=tmp_git_repo,
        )
        result = await skill.execute("/spec approve weather-skill", _ctx())

        assert result.success
        # Working tree clean — mutation is in HEAD now.
        porcelain = _git_stdout(tmp_git_repo, "status", "--porcelain")
        assert porcelain == "", f"expected clean tree, got: {porcelain!r}"
        # Spec yaml status is approved on disk.
        reloaded = yaml.safe_load(spec_path.read_text())
        assert reloaded["status"] == "approved"
        # HEAD message references the slug.
        msg = _git_stdout(tmp_git_repo, "log", "-1", "--pretty=%B")
        assert "weather-skill" in msg

    async def test_approve_without_repo_root_leaves_worktree_dirty_default(
        self, tmp_path: Path
    ) -> None:
        """Backward compat: existing callers without ``repo_root=`` still
        get the pre-Phase-19 behaviour — yaml is mutated on disk but no
        git operation runs."""
        tasks_dir = tmp_path / "tasks"
        spec_path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))

        skill = _make_skill(tasks_dir)  # no repo_root → opt-out
        result = await skill.execute("/spec approve weather-skill", _ctx())

        assert result.success
        reloaded = yaml.safe_load(spec_path.read_text())
        assert reloaded["status"] == "approved"
        # No assertion on git — there's no repo here.


class TestRejectAutoCommitsYaml:
    """Phase 19 — same auto-commit guarantee applies to ``/spec reject``."""

    async def test_reject_lands_yaml_commit(self, tmp_git_repo: Path) -> None:
        from src.skills.spec_command.skill import SpecCommandSkill

        tasks_dir = tmp_git_repo / "tasks"
        spec_path = _write_spec(tasks_dir, _spec_dict(slug="weather-skill"))
        subprocess_run_git(tmp_git_repo, "add", "-A")
        subprocess_run_git(tmp_git_repo, "commit", "-m", "init spec")

        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=None,
            repo_root=tmp_git_repo,
        )
        result = await skill.execute("/spec reject weather-skill out of scope", _ctx())

        assert result.success
        porcelain = _git_stdout(tmp_git_repo, "status", "--porcelain")
        assert porcelain == "", f"expected clean tree, got: {porcelain!r}"
        reloaded = yaml.safe_load(spec_path.read_text())
        assert reloaded["status"] == "rejected"
        msg = _git_stdout(tmp_git_repo, "log", "-1", "--pretty=%B")
        assert "weather-skill" in msg


def subprocess_run_git(repo: Path, *args: str) -> None:
    import subprocess

    subprocess.run(  # noqa: S603
        ["git", *args],  # noqa: S607
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )


class TestHelp:
    async def test_bare_spec_returns_help(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        result = await skill.execute("/spec", _ctx())

        assert result.success
        assert "list" in result.response.lower()
        assert "show" in result.response.lower()
        assert "approve" in result.response.lower()


class TestExecutionPlan:
    async def test_prepare_returns_lightweight_plan(self, tmp_path: Path) -> None:
        skill = _make_skill(tmp_path / "tasks")
        plan = await skill.prepare("/spec list", _ctx())

        assert plan.skill_name == "spec_command"
        assert plan.skill_type == "inline"
        # /spec list does not call LLM by default.
        assert plan.llm_calls_planned <= 1


class TestIntentClassifierFallback:
    async def test_intent_classifier_called_for_ambiguous_text(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        path = _write_spec(tasks_dir, _spec_dict(status="pending_approval"))

        from src.skills.spec_command.skill import (
            ApprovalIntent,
            SpecCommandSkill,
        )

        classifier = AsyncMock(return_value=ApprovalIntent.APPROVE)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        result = await skill.execute("ну окей пускай делает", _ctx())

        assert result.success
        classifier.assert_awaited_once()
        reloaded = yaml.safe_load(path.read_text())
        assert reloaded["status"] == "approved"

    async def test_intent_classifier_clarify_returns_question(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(tasks_dir, _spec_dict(status="pending_approval"))

        from src.skills.spec_command.skill import (
            ApprovalIntent,
            SpecCommandSkill,
        )

        classifier = AsyncMock(return_value=ApprovalIntent.CLARIFY)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        result = await skill.execute("хм, не уверен", _ctx())

        assert result.success
        # Clarify response should ask for explicit decision.
        assert "?" in result.response

    async def test_tier3_classifier_clarify_asks_short_free_text_question(
        self, tmp_path: Path
    ) -> None:
        tasks_dir = tmp_path / "tasks"
        _write_spec(
            tasks_dir,
            _spec_dict(slug="architecture-change", status="pending_approval", tier=3),
        )

        from src.skills.spec_command.skill import ApprovalIntent, SpecCommandSkill

        classifier = AsyncMock(return_value=ApprovalIntent.CLARIFY)
        skill = SpecCommandSkill(
            tasks_dir=tasks_dir,
            admin_user_id=12345,
            intent_classifier=classifier,
        )

        result = await skill.execute("хочу сначала понять риск", _ctx())

        assert result.success
        assert "Tier 3" in result.response
        assert "обычным текстом" in result.response
        assert "/spec approve" not in result.response
        assert "/spec show architecture-change" in result.response
