"""Contract + chain tests for ``ImplementSpecSkill`` (Phase 13).

The skill orchestrates the Editor cycle: validate the approved spec,
gate it through ``CapsEnforcer``, simulate when self-coding is off,
otherwise create the branch, invoke the Editor SDK adapter, commit
through ``CommitRunner``, and write the result back to the spec file.

Heavy dependencies (``BranchManager``/``CommitRunner``) work against the
``tmp_git_repo`` fixture from ``conftest.py``; the SDK runner is always
a mock so no external code-agent session is spawned.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock

import pytest
import yaml
from src.skills.base import AgentContext

pytestmark = pytest.mark.contract


# ---------------------------------------------------------------- helpers


def _ctx(*, user_id: int = 12345, mode: str = "personal", is_dry_run: bool = False):  # type: ignore[no-untyped-def]
    from src.skills.base import AgentContext

    return AgentContext(
        user_id=user_id,
        chat_id=user_id,
        mode=mode,  # type: ignore[arg-type]
        is_dry_run=is_dry_run,
    )


def _ctx_with_code_task(task_id: str) -> AgentContext:
    return AgentContext(
        user_id=12345,
        chat_id=12345,
        mode="personal",
        metadata={"chat_self_coding_code_task_id": task_id},
    )


def _write_spec(
    tasks_dir: Path,
    *,
    slug: str = "weather-skill",
    status: str = "approved",
    tier: int = 1,
    whitelist_paths: list[str] | None = None,
    extra: dict[str, Any] | None = None,
) -> Path:
    if whitelist_paths is None:
        whitelist_paths = [f"src/skills/{slug.replace('-', '_')}/skill.py"]
    payload: dict[str, Any] = {
        "slug": slug,
        "title": f"Add {slug}",
        "created_at": "2026-04-26T12:00:00+00:00",
        "created_by": "zhvusha",
        "tier": tier,
        "goal": (
            "Дать Жвуше команду /weather для admin_user_id. "
            "Проверка через failing test."
        ),
        "failing_test": {
            "file": f"tests/skills/{slug.replace('-', '_')}/test_contract.py",
            "name": "test_x",
            "spec": "Mock API call → assert response.",
        },
        "whitelist_paths": whitelist_paths,
        "blast_radius": ["new skill, no existing skill touched"],
        "rollback_path": ["git revert", f"rm -rf src/skills/{slug}/"],
        "preserve_behavior": [
            "Existing skills, fallbacks, tests and chat behaviour stay intact.",
        ],
        "allowed_simplifications": [],
        "rationale": "Spec is generated by Жвуша and needs archive evidence.",
        "source_provenance": [
            {
                "url": "local:test",
                "source_type": "local_repo",
                "trust_tier": "direct",
                "claim": "Test helper generated this spec.",
            }
        ],
        "status": status,
    }
    if extra:
        payload.update(extra)
    if status in {"approved", "in_progress", "done"}:
        payload["approved_at"] = "2026-04-26T12:30:00+00:00"
        payload["approved_by"] = "nikita"
    tasks_dir.mkdir(parents=True, exist_ok=True)
    path = tasks_dir / f"2026-04-26-{slug}.yaml"
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return path


def _make_skill(  # type: ignore[no-untyped-def]
    *,
    repo_root: Path,
    tasks_dir: Path | None = None,
    self_coding_enabled: bool = True,
    self_coding_max_tier: int = 2,
    caps_allowed: bool = True,
    sdk_runner: Any = None,
    block_publisher: Any = None,
    cycle_analyzer: Any = None,
    formal_gate: Any = None,
    reviewer: Any = None,
    adversarial_provider: Any = None,
    env_guard: Any = None,
):
    from src.skills.implement_spec.branch_manager import BranchManager
    from src.skills.implement_spec.caps_enforcer import (
        CapsCheckResult,
        CapsEnforcer,
    )
    from src.skills.implement_spec.commit_runner import CommitRunner
    from src.skills.implement_spec.sdk_runner import EditorSdkResult
    from src.skills.implement_spec.skill import ImplementSpecSkill

    caps = AsyncMock(spec=CapsEnforcer)
    caps.check = AsyncMock(
        return_value=CapsCheckResult(
            allowed=caps_allowed,
            reason=None if caps_allowed else "лимит исчерпан",
        )
    )
    caps.record = AsyncMock(return_value=None)

    runner = sdk_runner or AsyncMock(return_value=EditorSdkResult(text="ok"))

    return ImplementSpecSkill(
        tasks_dir=tasks_dir or (repo_root / "tasks"),
        project_root=repo_root,
        admin_user_id=12345,
        self_coding_enabled=self_coding_enabled,
        self_coding_max_tier=self_coding_max_tier,
        caps_enforcer=caps,
        branch_manager=BranchManager(repo_root=repo_root, base_branch="main"),
        commit_runner=CommitRunner(repo_root=repo_root),
        sdk_runner=runner,
        block_publisher=block_publisher,
        cycle_analyzer=cycle_analyzer,
        formal_gate=formal_gate,
        reviewer=reviewer,
        adversarial_provider=adversarial_provider,
        env_guard=env_guard,
    )


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # noqa: S603 — args literal, repo is tmp_path
        ["git", *args],  # noqa: S607 — git on PATH
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )


# ---------------------------------------------------------------- contract


class TestContract:
    def test_inherits_delegated_skill(self) -> None:
        from src.skills.base import BaseSkill, DelegatedSkill
        from src.skills.implement_spec.skill import ImplementSpecSkill

        assert issubclass(ImplementSpecSkill, DelegatedSkill)
        assert issubclass(ImplementSpecSkill, BaseSkill)

    def test_skill_type_is_delegated(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        assert ImplementSpecSkill.skill_type == "delegated"

    def test_executor_is_codex_cli(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        assert ImplementSpecSkill.executor == "codex_cli"

    def test_approval_policy_is_required(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        assert ImplementSpecSkill.approval_policy == "required"

    def test_modifies_no_core_capabilities(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        assert ImplementSpecSkill.modifies == []

    def test_manifest_loads_and_matches_class(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.manifest import (
            load_manifest_for_skill_class,
            validate_manifest_matches_class,
        )

        manifest = load_manifest_for_skill_class(ImplementSpecSkill)
        validate_manifest_matches_class(manifest, ImplementSpecSkill)
        assert manifest.name == "implement_spec"
        assert manifest.executor == "codex_cli"


# ---------------------------------------------------------------- can_handle


class TestCanHandle:
    async def test_admin_personal_spec_run_full_score(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        assert await skill.can_handle("/spec_run weather-skill", _ctx()) == 1.0

    async def test_admin_personal_implement_spec_full_score(
        self, tmp_git_repo: Path
    ) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        assert await skill.can_handle("/implement_spec weather-skill", _ctx()) == 1.0

    async def test_non_admin_zero(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        assert await skill.can_handle("/spec_run x", _ctx(user_id=99)) == 0.0

    async def test_assistant_mode_zero(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        assert await skill.can_handle("/spec_run x", _ctx(mode="assistant")) == 0.0

    async def test_unrelated_message_zero(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        assert await skill.can_handle("привет, как дела?", _ctx()) == 0.0

    async def test_natural_approved_spec_run_routes_high_confidence(
        self, tmp_git_repo: Path
    ) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        assert (
            await skill.can_handle("запусти approved spec weather-skill", _ctx()) >= 0.9
        )
        assert (
            await skill.can_handle("обсудим approved spec weather-skill", _ctx()) == 0.0
        )


# ---------------------------------------------------------------- execute guards


class TestExecuteGuards:
    async def test_missing_slug_returns_help(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        result = await skill.execute("/spec_run", _ctx())
        assert result.success is False
        assert "slug" in result.response.lower()

    async def test_spec_not_found_returns_error(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        result = await skill.execute("/spec_run does-not-exist", _ctx())
        assert result.success is False
        assert "не найден" in result.response or "not found" in result.response.lower()

    async def test_natural_spec_run_uses_existing_approved_slug(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(tasks, slug="weather-skill", status="approved")
        skill = _make_skill(repo_root=tmp_git_repo, self_coding_enabled=False)

        result = await skill.execute("запусти approved spec weather-skill", _ctx())

        assert result.success is True
        assert "weather-skill" in result.response

    async def test_natural_spec_run_tolerates_extra_spacing(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(tasks, slug="weather-skill", status="approved")
        skill = _make_skill(repo_root=tmp_git_repo, self_coding_enabled=False)

        result = await skill.execute("запусти   approved   spec: weather-skill", _ctx())

        assert result.success is True
        assert "weather-skill" in result.response

    async def test_natural_spec_run_without_slug_requests_missing_input(
        self,
        tmp_git_repo: Path,
    ) -> None:
        from src.skills.invocation import (
            InMemorySkillApprovalStore,
            SkillInvocationService,
        )

        async def _approval_classifier(text: str) -> str:
            del text
            return "yes"

        skill = _make_skill(repo_root=tmp_git_repo, self_coding_enabled=False)
        service = SkillInvocationService(
            approval_store=InMemorySkillApprovalStore(),
            approval_classifier=_approval_classifier,
            is_skill_allowed=lambda _name, _mode: True,
        )

        outcome = await service.dispatch("запусти spec", _ctx(), [skill])

        assert outcome.result is not None
        assert outcome.result.metadata["requires_user_input"] is True
        assert outcome.result.metadata["missing_fields"] == ["spec_slug"]

    async def test_unapproved_spec_rejected(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(tasks, slug="weather-skill", status="pending_approval")
        skill = _make_skill(repo_root=tmp_git_repo)
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success is False
        assert "approve" in result.response.lower()

    async def test_tier_above_max_rejected(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=2,
            whitelist_paths=["src/llm/router.py"],
        )
        skill = _make_skill(repo_root=tmp_git_repo, self_coding_max_tier=1)
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success is False
        assert "tier" in result.response.lower()

    async def test_tier_3_runs_when_max_tier_allows(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=3,
            whitelist_paths=[
                "src/skills/base.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec: tier3-weather")
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_max_tier=3,
            sdk_runner=_editor_writes_files(),
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success is True, result.response

    async def test_caps_blocked_returns_reason(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(tasks, slug="weather-skill", status="approved")
        skill = _make_skill(repo_root=tmp_git_repo, caps_allowed=False)
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success is False
        assert "лимит" in result.response.lower()


# ---------------------------------------------------------------- dry-run


class TestExecuteDryRun:
    async def test_self_coding_disabled_simulates(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(tasks, slug="weather-skill", status="approved")
        sdk = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_enabled=False,
            sdk_runner=sdk,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success is True
        assert "dry-run" in result.response.lower()
        # SDK never called.
        sdk.assert_not_awaited()
        # No new branch created.
        branches = _git(tmp_git_repo, "branch", "--list").stdout
        assert "zhvusha/weather-skill" not in branches

    async def test_context_dry_run_simulates(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(tasks, slug="weather-skill", status="approved")
        sdk = AsyncMock()
        skill = _make_skill(repo_root=tmp_git_repo, sdk_runner=sdk)
        result = await skill.execute("/spec_run weather-skill", _ctx(is_dry_run=True))
        assert result.success is True
        sdk.assert_not_awaited()


# ---------------------------------------------------------------- happy path


def _editor_writes_files(*, message: str = "done"):  # type: ignore[no-untyped-def]
    """Build an SDK runner that pretends the Editor wrote each whitelist file."""
    from src.skills.implement_spec.sdk_runner import EditorSdkResult

    async def runner(*args: Any, **kwargs: Any) -> Any:
        del args
        cwd = kwargs["cwd"]
        for rel in kwargs["whitelist_paths"]:
            full = cwd / rel
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text("editor wrote this\n", encoding="utf-8")
        return EditorSdkResult(text=message)

    return runner


def _editor_writes_first_whitelist_file(*, message: str = "done"):  # type: ignore[no-untyped-def]
    """Build an SDK runner that writes only the first whitelist file."""
    from src.skills.implement_spec.sdk_runner import EditorSdkResult

    async def runner(*args: Any, **kwargs: Any) -> Any:
        del args
        cwd = kwargs["cwd"]
        rel = kwargs["whitelist_paths"][0]
        full = cwd / rel
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text("editor wrote this\n", encoding="utf-8")
        return EditorSdkResult(text=message)

    return runner


def _editor_writes_only_outside_whitelist(*, message: str = "bad diff"):  # type: ignore[no-untyped-def]
    from src.skills.implement_spec.sdk_runner import EditorSdkResult

    async def runner(*args: Any, **kwargs: Any) -> Any:
        del args
        outside = kwargs["cwd"] / "outside.txt"
        outside.write_text("should be inspectable\n", encoding="utf-8")
        return EditorSdkResult(text=message)

    return runner


def _editor_writes_attempts(
    contents: list[str],
    *,
    prompts: list[str] | None = None,
    message_prefix: str = "attempt",
):  # type: ignore[no-untyped-def]
    """Build an SDK runner that writes one content value per invocation."""
    from src.skills.implement_spec.sdk_runner import EditorSdkResult

    async def runner(*args: Any, **kwargs: Any) -> Any:
        del args
        if prompts is not None:
            prompts.append(kwargs["user_prompt"])
            attempt = len(prompts)
        else:
            attempt = 1
        content = contents[min(attempt - 1, len(contents) - 1)]
        cwd = kwargs["cwd"]
        rel = kwargs["whitelist_paths"][0]
        full = cwd / rel
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content, encoding="utf-8")
        return EditorSdkResult(text=f"{message_prefix} {attempt}")

    return runner


def _editor_changes_env(*, message: str = "changed env"):  # type: ignore[no-untyped-def]
    from src.skills.implement_spec.sdk_runner import EditorSdkResult

    async def runner(*args: Any, **kwargs: Any) -> Any:
        del args
        env_path = kwargs["cwd"] / ".env"
        env_path.write_text(
            "BOT_TOKEN=fake_changed\nBOT_RESTART_ENABLED=true\n",
            encoding="utf-8",
        )
        return EditorSdkResult(text=message)

    return runner


def _editor_writes_file_and_allowed_env(*, message: str = "changed env"):  # type: ignore[no-untyped-def]
    from src.skills.implement_spec.sdk_runner import EditorSdkResult

    async def runner(*args: Any, **kwargs: Any) -> Any:
        del args
        cwd = kwargs["cwd"]
        rel = kwargs["whitelist_paths"][0]
        full = cwd / rel
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text("editor wrote this\n", encoding="utf-8")
        (cwd / ".env").write_text(
            "BOT_RESTART_ENABLED=true\n",
            encoding="utf-8",
        )
        return EditorSdkResult(text=message)

    return runner


def _editor_emits_progress(*, message: str = "done"):  # type: ignore[no-untyped-def]
    async def runner(*args: Any, **kwargs: Any) -> Any:
        callback = kwargs["progress_callback"]
        await callback("Сейчас дочитаю затронутые файлы целиком и добавлю RED-тесты.")
        return await _editor_writes_files(message=message)(*args, **kwargs)

    return runner


class TestExecuteHappyPath:
    async def test_creates_branch_and_commits(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        # Commit the spec file as Никита so the SDK starts from a clean tree.
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec: weather-skill")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success, result.response

        # Self-coding must not leave the live repo checked out on a
        # long-lived ``zhvusha/<slug>`` branch.
        branch = _git(tmp_git_repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
        assert branch == "main"
        self_branches = _git(
            tmp_git_repo, "branch", "--list", "zhvusha/weather-skill*"
        ).stdout
        assert self_branches.strip() == ""

        # Commit landed under zhvusha-coder author.
        author = _git(tmp_git_repo, "log", "-1", "--pretty=%ae").stdout.strip()
        assert author == "zhvusha@local"

        # Spec file updated to status=done.
        from src.skills.spec_command.parser import SpecModel, SpecStatus

        reread = SpecModel.model_validate(
            yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        )
        assert reread.status == SpecStatus.DONE
        assert reread.branch == "main"
        assert reread.commit_sha
        _git(tmp_git_repo, "cat-file", "-e", f"{reread.commit_sha}^{{commit}}")
        assert set(result.metadata["changed_files"]) == {
            "src/skills/weather_skill/skill.py",
            "tasks/2026-04-26-weather-skill.yaml",
        }
        assert result.metadata["backend"] == "codex_cli"
        assert result.metadata["tests"] == [
            "commit gate: tests, style and types passed",
            "test_count_delta: +0",
        ]
        assert result.metadata["failed_repairs"] == []
        assert result.metadata["risk_review"]
        assert result.metadata["reasoning_summary"] == "done"

    async def test_working_tree_clean_after_cycle(self, tmp_git_repo: Path) -> None:
        """Bug regression: after a successful cycle the spec.yaml status
        update must land in a commit, not be left dirty in the worktree.

        Otherwise the next ``/spec_run`` trips ``BranchManager._assert_clean_tree``
        and the agent can't run two cycles in a row without a manual commit.
        """
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec: weather-skill")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success, result.response

        porcelain = _git(tmp_git_repo, "status", "--porcelain").stdout.strip()
        assert porcelain == "", (
            f"working tree dirty after cycle:\n{porcelain}\n"
            "Expected the spec.yaml status update to be committed."
        )

    async def test_checkpoints_untracked_active_spec_before_worktree(
        self, tmp_git_repo: Path
    ) -> None:
        """Architect may have just written the approved spec into tasks/.

        That controlled spec artifact must not block Editor's isolated worktree
        guard, but arbitrary dirty files still must.
        """
        tasks = tmp_git_repo / "tasks"
        _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success, result.response

        porcelain = _git(tmp_git_repo, "status", "--porcelain").stdout.strip()
        assert porcelain == ""
        checkpoint = _git(
            tmp_git_repo,
            "log",
            "--grep=checkpoint approved spec",
            "--oneline",
        ).stdout.strip()
        assert checkpoint

    async def test_extra_dirty_file_still_blocks_spec_checkpoint(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        (tmp_git_repo / "error.md").write_text("traceback\n", encoding="utf-8")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert not result.success
        assert "Временная рабочая копия не создана" in result.response
        checkpoint = _git(
            tmp_git_repo,
            "log",
            "--grep=checkpoint approved spec",
            "--oneline",
        ).stdout.strip()
        assert checkpoint == ""

    async def test_records_caps_invocation(self, tmp_git_repo: Path) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
        )
        await skill.execute("/spec_run weather-skill", _ctx())
        # Caps record() called exactly once.
        skill._caps.record.assert_awaited_once()

    async def test_records_cycle_archive_after_success(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        analyzer = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(message="archive me"),
            cycle_analyzer=analyzer,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success
        analyzer.record_success.assert_awaited_once()
        kwargs = analyzer.record_success.await_args.kwargs
        assert kwargs["commit_sha"]
        assert kwargs["backend"] == "codex_cli"

    async def test_spec_run_is_wrapper_over_run_slug(self, tmp_git_repo: Path) -> None:
        from src.skills.base import SkillResult

        calls: list[str] = []
        skill = _make_skill(repo_root=tmp_git_repo)

        async def run_slug(slug: str, context: Any) -> SkillResult:
            del context
            calls.append(slug)
            return SkillResult(success=True, response="wrapped")

        skill.run_slug = run_slug  # type: ignore[method-assign]

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success
        assert result.response == "wrapped"
        assert calls == ["weather-skill"]

    async def test_live_env_activation_applies_allowed_key_and_reports_audit(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        (tmp_git_repo / ".env").write_text(
            "BOT_RESTART_ENABLED=false\n",
            encoding="utf-8",
        )
        (tmp_git_repo / ".gitignore").write_text(".env\n", encoding="utf-8")
        _git(tmp_git_repo, "add", ".gitignore")
        _git(tmp_git_repo, "commit", "-m", "ignore env")
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
            extra={
                "live_env_activation": True,
                "live_env_keys": ["BOT_RESTART_ENABLED"],
            },
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_file_and_allowed_env(),
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        assert (tmp_git_repo / ".env").read_text(encoding="utf-8") == (
            "BOT_RESTART_ENABLED=true\n"
        )
        audit_path = Path(result.metadata["env_audit_path"])
        assert audit_path.exists()
        assert "BOT_RESTART_ENABLED" in audit_path.read_text(encoding="utf-8")

    async def test_records_cycle_archive_after_sdk_failure(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.sdk_runner import SDKUnavailableError

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        async def failing_sdk(*args: Any, **kwargs: Any) -> Any:
            del args, kwargs
            raise SDKUnavailableError("codex_cli", "missing binary")

        analyzer = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=failing_sdk,
            cycle_analyzer=analyzer,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert not result.success
        analyzer.record_failure.assert_awaited_once()
        kwargs = analyzer.record_failure.await_args.kwargs
        assert kwargs["branch_name"].startswith("isolated:")
        assert "missing binary" in kwargs["reason"]

    async def test_failed_commit_preserves_worktree_for_manual_inspection(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_only_outside_whitelist(),
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert not result.success
        preserved_path = Path(result.metadata["failed_worktree_path"])
        assert preserved_path.exists()
        assert (preserved_path / "outside.txt").read_text(encoding="utf-8") == (
            "should be inspectable\n"
        )
        assert Path(result.metadata["failed_worktree_status_path"]).exists()
        assert Path(result.metadata["failed_worktree_diff_path"]).exists()
        assert str(preserved_path) in result.response

        raw = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        assert str(preserved_path) in raw["failed_attempts"][-1]

    def test_mark_failed_keeps_useful_head_and_tail_of_long_reason(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        raw = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        skill = _make_skill(repo_root=tmp_git_repo)

        long_reason = "head " + ("x" * 3000) + " tail: real hook error"
        skill._mark_failed(
            spec_path,
            raw,
            branch_name="isolated:weather-skill:test",
            reason=long_reason,
        )

        reread = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        stored = reread["failed_attempts"][-1]
        assert stored.startswith("head ")
        assert "tail: real hook error" in stored
        assert len(stored) < len(long_reason)

    async def test_optional_reviewer_runs_after_commit(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            return_value=ReviewVerdict(verdict="approve", rationale="ok")
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
            reviewer=reviewer,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success
        reviewer.review.assert_awaited_once()

    async def test_reviewer_reads_live_spec_when_untracked_spec_not_in_worktree(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict

        tasks = tmp_git_repo / "tasks"
        _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        (tmp_git_repo / "operator-note.md").write_text(
            "unrelated dirty state\n", encoding="utf-8"
        )

        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            return_value=ReviewVerdict(verdict="approve", rationale="ok")
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
            reviewer=reviewer,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        request = reviewer.review.await_args.args[0]
        assert "slug: weather-skill" in request.spec_yaml
        assert (tmp_git_repo / "operator-note.md").read_text(
            encoding="utf-8"
        ) == "unrelated dirty state\n"

    async def test_formal_gate_receives_actual_commit_files_and_test_counts(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.formal_gates import FormalGateVerdict

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "src/skills/weather_skill/unused.py",
            ],
        )
        test_path = tmp_git_repo / "tests/test_existing.py"
        test_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.write_text(
            "def test_existing():\n    assert True\n", encoding="utf-8"
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "add", str(test_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        seen_inputs = []

        def formal_gate(inputs: Any) -> Any:
            seen_inputs.append(inputs)
            return FormalGateVerdict(passed=True)

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_first_whitelist_file(),
            formal_gate=formal_gate,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        inputs = seen_inputs[0]
        assert inputs.baseline_test_count == 1
        assert inputs.current_test_count == 1
        assert inputs.changed_files == ["src/skills/weather_skill/skill.py"]
        assert inputs.audit_log["commit_sha"]

    async def test_reviewer_receives_full_commit_diff_not_just_sha(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            return_value=ReviewVerdict(verdict="approve", rationale="ok")
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(message="implemented with tests"),
            reviewer=reviewer,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        request = reviewer.review.await_args.args[0]
        assert "diff --git" in request.diff
        assert "editor wrote this" in request.diff
        assert "implemented with tests" in request.test_output
        assert request.audit_log["changed_files"]

    async def test_reviewer_reject_retries_editor_with_repair_context(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=3,
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        prompts: list[str] = []
        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            side_effect=[
                ReviewVerdict(
                    verdict="reject",
                    rationale=(
                        "Публикация изображения идёт раньше текста и может "
                        "оставить orphan media."
                    ),
                ),
                ReviewVerdict(verdict="approve", rationale="ok"),
            ]
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_max_tier=3,
            sdk_runner=_editor_writes_attempts(
                ["bad media-first implementation\n", "fixed text-first publish\n"],
                prompts=prompts,
            ),
            reviewer=reviewer,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        assert len(prompts) == 2
        assert "# Repair context" not in prompts[0]
        assert "# Repair context" in prompts[1]
        assert "orphan media" in prompts[1]
        assert "bad media-first implementation" in prompts[1]
        assert reviewer.review.await_count == 2
        assert (tmp_git_repo / "src/skills/weather_skill/skill.py").read_text(
            encoding="utf-8"
        ) == "fixed text-first publish\n"

    async def test_repair_attempt_resumes_persistent_editor_session(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict
        from src.skills.implement_spec.sdk_runner import EditorSdkResult

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=3,
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        session_ids: list[str] = []
        persist_flags: list[bool] = []

        async def sdk_runner(*args: Any, **kwargs: Any) -> EditorSdkResult:
            del args
            session_ids.append(kwargs["session_id"])
            persist_flags.append(kwargs["persist_session"])
            attempt = len(session_ids)
            full = kwargs["cwd"] / kwargs["whitelist_paths"][0]
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(f"attempt {attempt}\n", encoding="utf-8")
            return EditorSdkResult(
                text=f"attempt {attempt}",
                session_id=f"codex-editor-thread-{attempt}",
            )

        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            side_effect=[
                ReviewVerdict(verdict="reject", rationale="first attempt is weak"),
                ReviewVerdict(verdict="approve", rationale="ok"),
            ]
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_max_tier=3,
            sdk_runner=sdk_runner,
            reviewer=reviewer,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        assert persist_flags == [True, True]
        assert session_ids == ["", "codex-editor-thread-1"]
        assert (tmp_git_repo / "src/skills/weather_skill/skill.py").read_text(
            encoding="utf-8"
        ) == "attempt 2\n"

    async def test_next_run_resumes_preserved_worktree_and_editor_session(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict
        from src.skills.implement_spec.sdk_runner import EditorSdkResult

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=3,
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        calls: list[dict[str, Any]] = []

        async def sdk_runner(*args: Any, **kwargs: Any) -> EditorSdkResult:
            del args
            calls.append(
                {
                    "cwd": kwargs["cwd"],
                    "session_id": kwargs["session_id"],
                    "persist_session": kwargs["persist_session"],
                }
            )
            attempt = len(calls)
            full = kwargs["cwd"] / kwargs["whitelist_paths"][0]
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(
                "fixed after preserved resume\n"
                if attempt == 3
                else f"bad attempt {attempt}\n",
                encoding="utf-8",
            )
            return EditorSdkResult(
                text=f"attempt {attempt}",
                session_id=kwargs["session_id"] or "codex-editor-thread-1",
            )

        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            side_effect=[
                ReviewVerdict(verdict="reject", rationale="first still weak"),
                ReviewVerdict(verdict="reject", rationale="second still weak"),
                ReviewVerdict(verdict="approve", rationale="ok"),
            ]
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_max_tier=3,
            sdk_runner=sdk_runner,
            reviewer=reviewer,
        )

        first = await skill.execute("/spec_run weather-skill", _ctx())

        assert not first.success
        assert first.metadata["editor_codex_session_id"] == "codex-editor-thread-1"
        preserved_path = Path(first.metadata["failed_worktree_path"])
        assert preserved_path.exists()

        raw = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        raw["status"] = "approved"
        raw["approved_at"] = "2026-04-26T12:45:00+00:00"
        raw["approved_by"] = "nikita"
        spec_path.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")

        resume_context = AgentContext(
            user_id=12345,
            chat_id=12345,
            mode="personal",
            metadata={
                "chat_self_coding_editor_codex_session_id": first.metadata[
                    "editor_codex_session_id"
                ],
                "chat_self_coding_failed_worktree_path": first.metadata[
                    "failed_worktree_path"
                ],
                "chat_self_coding_failed_worktree_label": first.metadata[
                    "failed_worktree_label"
                ],
                "chat_self_coding_failed_worktree_base_branch": first.metadata[
                    "failed_worktree_base_branch"
                ],
                "chat_self_coding_failed_worktree_base_sha": first.metadata[
                    "failed_worktree_base_sha"
                ],
            },
        )

        second = await skill.execute("/spec_run weather-skill", resume_context)

        assert second.success, second.response
        assert len(calls) == 3
        assert calls[2]["cwd"] == preserved_path
        assert calls[2]["session_id"] == "codex-editor-thread-1"
        assert calls[2]["persist_session"] is True
        assert (tmp_git_repo / "src/skills/weather_skill/skill.py").read_text(
            encoding="utf-8"
        ) == "fixed after preserved resume\n"
        assert not preserved_path.exists()

    async def test_commit_gate_failure_retries_editor_with_repair_context(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        prompts: list[str] = []

        async def sdk_runner(*args: Any, **kwargs: Any) -> Any:
            from src.skills.implement_spec.sdk_runner import EditorSdkResult

            del args
            prompts.append(kwargs["user_prompt"])
            if len(prompts) == 1:
                (kwargs["cwd"] / "outside.txt").write_text(
                    "outside whitelist\n",
                    encoding="utf-8",
                )
            else:
                full = kwargs["cwd"] / kwargs["whitelist_paths"][0]
                full.parent.mkdir(parents=True, exist_ok=True)
                full.write_text("fixed whitelist file\n", encoding="utf-8")
            return EditorSdkResult(text=f"attempt {len(prompts)}")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=sdk_runner,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        assert len(prompts) == 2
        assert "Commit gate" in prompts[1]
        assert "nothing to commit" in prompts[1]
        assert not (tmp_git_repo / "outside.txt").exists()
        assert (tmp_git_repo / "src/skills/weather_skill/skill.py").read_text(
            encoding="utf-8"
        ) == "fixed whitelist file\n"

    async def test_sdk_backend_failure_stops_without_hidden_retry(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=["src/skills/weather_skill/skill.py"],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        prompts: list[str] = []

        async def sdk_runner(*args: Any, **kwargs: Any) -> Any:
            del args
            prompts.append(kwargs["user_prompt"])
            full = kwargs["cwd"] / kwargs["whitelist_paths"][0]
            full.parent.mkdir(parents=True, exist_ok=True)
            if len(prompts) == 1:
                full.write_text("partial sdk edit before crash\n", encoding="utf-8")
                raise RuntimeError("codex process exited after partial edit")
            raise AssertionError(
                "SDK backend failures must not auto-start another editor"
            )

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=sdk_runner,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert not result.success
        assert len(prompts) == 1
        assert result.metadata["auto_retryable"] == "false"
        assert result.metadata["failure_category"] == "technical_blocker"
        assert result.metadata["needs_user_decision"] == "false"
        status_text = Path(result.metadata["failed_worktree_status_path"]).read_text(
            encoding="utf-8"
        )
        assert "src/skills/weather_skill/skill.py" in status_text

    async def test_repair_loop_exhaustion_preserves_final_commit_diff(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.implement_spec.reviewer import ReviewVerdict

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=3,
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        prompts: list[str] = []
        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            return_value=ReviewVerdict(
                verdict="reject",
                rationale="still accepts localhost screenshots",
            )
        )
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_max_tier=3,
            sdk_runner=_editor_writes_attempts(
                ["attempt 1\n", "attempt 2\n", "attempt 3\n"],
                prompts=prompts,
            ),
            reviewer=reviewer,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert not result.success
        assert "Repair attempts exhausted" in result.response
        assert result.metadata["failure_category"] == "technical_blocker"
        assert result.metadata["auto_retryable"] == "false"
        assert result.metadata["needs_user_decision"] == "false"
        assert "decision_question" not in result.metadata
        assert len(prompts) == 2
        assert reviewer.review.await_count == 2
        preserved_path = Path(result.metadata["failed_worktree_path"])
        diff_text = Path(result.metadata["failed_worktree_diff_path"]).read_text(
            encoding="utf-8"
        )
        assert preserved_path.exists()
        assert "attempt 2" in diff_text
        raw = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        assert "still accepts localhost screenshots" in raw["failed_attempts"][-1]

    async def test_reviewer_reject_that_needs_product_choice_stops_after_one_attempt(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.chat_self_coding.events import BlockEventType
        from src.skills.implement_spec.reviewer import ReviewVerdict

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=3,
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        prompts: list[str] = []
        reviewer = AsyncMock()
        reviewer.review = AsyncMock(
            return_value=ReviewVerdict(
                verdict="reject",
                rationale=(
                    "GPT Image API не позволяет сделать эту функцию через текущую "
                    "подписку; нужно выбрать, как будет происходить генерация."
                ),
            )
        )
        publisher = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            self_coding_max_tier=3,
            sdk_runner=_editor_writes_attempts(
                ["attempt 1\n", "attempt 2\n", "attempt 3\n"],
                prompts=prompts,
            ),
            reviewer=reviewer,
            block_publisher=publisher,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert not result.success
        assert len(prompts) == 1
        assert reviewer.review.await_count == 1
        assert result.metadata["failure_category"] == "needs_user_decision"
        assert result.metadata["auto_retryable"] == "false"
        assert result.metadata["needs_user_decision"] == "true"
        assert "decision_question" in result.metadata
        error_events = [
            call.args[0]
            for call in publisher.publish.await_args_list
            if call.args[0].event_type == BlockEventType.ERROR
        ]
        assert len(error_events) == 1
        assert "подписку" in error_events[0].payload["reason"]

    def test_english_reviewer_decision_markers_require_user_choice(self) -> None:
        from src.skills.implement_spec.skill import _failure_requires_user_decision

        assert _failure_requires_user_decision(
            "Reviewer verdict `reject`",
            (
                "Needs user decision: GPT Images are not enabled for this account; "
                "choose the image generation provider before continuing."
            ),
        )
        assert not _failure_requires_user_decision(
            "Reviewer verdict `reject`",
            (
                "Blockers remain: public-source safety validates only the initial "
                "URL and must validate the final browser destination."
            ),
        )

    async def test_tier2_invokes_adversarial_provider_and_prompts_editor(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.adversarial_test_gen.generator import AdversarialTestDraft

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            tier=2,
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        adversarial_provider = AsyncMock()
        adversarial_provider.generate = AsyncMock(
            return_value=[
                AdversarialTestDraft(
                    archive_slug="weather-failed-node",
                    test_file="tests/adversarial/test_weather.py",
                    test_name="test_adversarial_weather",
                    body="def test_adversarial_weather():\n    assert True\n",
                    rationale="Keep the weather failure anchored.",
                )
            ]
        )
        seen_prompts: list[str] = []

        async def sdk_runner(*args: Any, **kwargs: Any) -> Any:
            del args
            seen_prompts.append(kwargs["user_prompt"])
            return await _editor_writes_files()(**kwargs)

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=sdk_runner,
            adversarial_provider=adversarial_provider,
        )

        result = await skill.execute("/spec_run weather-skill", _ctx())

        assert result.success, result.response
        adversarial_provider.generate.assert_awaited_once()
        assert "weather-failed-node" in seen_prompts[0]
        assert "Keep the weather failure anchored" in seen_prompts[0]

    async def test_runtime_chat_context_is_prompted_to_editor(
        self, tmp_git_repo: Path
    ) -> None:
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        seen_prompts: list[str] = []

        async def sdk_runner(*args: Any, **kwargs: Any) -> Any:
            del args
            seen_prompts.append(kwargs["user_prompt"])
            return await _editor_writes_files()(**kwargs)

        skill = _make_skill(repo_root=tmp_git_repo, sdk_runner=sdk_runner)
        context = _ctx()
        context = AgentContext(
            user_id=context.user_id,
            chat_id=context.chat_id,
            mode=context.mode,
            metadata={
                "chat_self_coding_recent_messages": (
                    "Никита: после ошибки не обсуждать, а чинить автоматически",
                    "Жвуша: поняла, следующий проход должен учитывать это",
                )
            },
        )

        result = await skill.execute("/spec_run weather-skill", context)

        assert result.success, result.response
        assert "# /код recovery discussion before this run" in seen_prompts[0]
        assert "чинить автоматически" in seen_prompts[0]


class TestEnvGuardIntegration:
    async def test_blocks_and_restores_protected_env_key(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.chat_self_coding.events import BlockEventType
        from src.skills.implement_spec.env_guard import EnvGuard

        env_path = tmp_git_repo / ".env"
        env_path.write_text(
            "BOT_TOKEN=fake_original\nBOT_RESTART_ENABLED=false\n",
            encoding="utf-8",
        )
        (tmp_git_repo / ".gitignore").write_text(".env\n", encoding="utf-8")
        guard = EnvGuard.from_env_file(env_path)

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="env-guard",
            status="approved",
            whitelist_paths=[
                ".env",
                "tasks/2026-04-26-env-guard.yaml",
            ],
        )
        _git(tmp_git_repo, "add", ".gitignore")
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        publisher = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_changes_env(),
            block_publisher=publisher,
            env_guard=guard,
        )

        result = await skill.execute("/spec_run env-guard", _ctx())

        assert not result.success
        assert "BOT_TOKEN" in result.response
        assert result.metadata["failure_category"] == "needs_host_ops"
        assert env_path.read_text(encoding="utf-8") == (
            "BOT_TOKEN=fake_original\nBOT_RESTART_ENABLED=false\n"
        )
        error_evt = next(
            call.args[0]
            for call in publisher.publish.await_args_list
            if call.args[0].event_type == BlockEventType.ERROR
        )
        assert "BOT_TOKEN" in error_evt.payload["reason"]

    def test_editor_prompt_includes_protected_env_instruction(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        prompt = ImplementSpecSkill._build_system_prompt()

        assert "BOT_TOKEN" in prompt
        assert "*_API_KEY" in prompt
        assert "protected .env" in prompt.lower()


# ---------------------------------------------------------------- block events


class TestBlockEventPublishing:
    """Phase 40 — implement_spec emits per-stage block events."""

    async def test_publishes_preparation_implementation_done_in_order(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.chat_self_coding.events import BlockEventType

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        publisher = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
            block_publisher=publisher,
        )
        result = await skill.execute(
            "/spec_run weather-skill",
            _ctx_with_code_task("code-task-fixed"),
        )
        assert result.success, result.response

        published_types = [
            call.args[0].event_type for call in publisher.publish.await_args_list
        ]
        assert published_types == [
            BlockEventType.PREPARATION,
            BlockEventType.IMPLEMENTATION,
            BlockEventType.IMPLEMENTATION,
            BlockEventType.IMPLEMENTATION,
            BlockEventType.DONE,
        ]
        first_evt = publisher.publish.await_args_list[0].args[0]
        assert first_evt.task_id == "code-task-fixed"
        assert first_evt.payload["percent"] == 15
        assert "base: main" in first_evt.payload["facts"]
        assert "isolation: worktree" in first_evt.payload["facts"]

        implementation_payloads = [
            call.args[0].payload
            for call in publisher.publish.await_args_list
            if call.args[0].event_type == BlockEventType.IMPLEMENTATION
        ]
        assert [payload["percent"] for payload in implementation_payloads] == [
            40,
            70,
            85,
        ]
        assert "baseline tests: 0" in implementation_payloads[0]["facts"]
        assert "backend: codex_cli" in implementation_payloads[1]["facts"]
        assert any(
            fact.startswith("commit: ") for fact in implementation_payloads[2]["facts"]
        )

    async def test_publishes_human_editor_session_status(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.chat_self_coding.events import BlockEventType

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        publisher = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_emits_progress(),
            block_publisher=publisher,
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success, result.response

        details = [
            call.args[0].payload["detail"]
            for call in publisher.publish.await_args_list
            if call.args[0].event_type == BlockEventType.IMPLEMENTATION
        ]
        note_payloads = [
            call.args[0].payload
            for call in publisher.publish.await_args_list
            if call.args[0].payload.get("message_kind") == "note"
        ]
        assert any("RED-тесты" in detail for detail in details)
        assert note_payloads
        assert not any(
            "Explored" in detail or "Working (" in detail for detail in details
        )

    async def test_done_event_carries_files_and_checks(
        self, tmp_git_repo: Path
    ) -> None:
        from src.skills.chat_self_coding.events import BlockEventType

        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        publisher = AsyncMock()
        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
            block_publisher=publisher,
        )
        await skill.execute("/spec_run weather-skill", _ctx())

        done_evt = next(
            call.args[0]
            for call in publisher.publish.await_args_list
            if call.args[0].event_type == BlockEventType.DONE
        )
        assert "files" in done_evt.payload
        assert "checks" in done_evt.payload
        assert done_evt.payload["branch"] == "main"
        assert done_evt.payload["commit_sha"]
        assert done_evt.payload["backend"] == "codex_cli"
        assert done_evt.payload["test_count_delta"] == 0
        assert done_evt.payload["allowed_simplifications"] == []
        # All three checks reported as passed (commit gate already
        # verified them — failure would have raised CommitRunnerError).
        verdicts = dict(done_evt.payload["checks"])
        assert verdicts == {"тесты": True, "стиль": True, "типы": True}

    async def test_default_publisher_is_noop_no_crash(self, tmp_git_repo: Path) -> None:
        """No publisher injected → cycle runs unchanged."""
        tasks = tmp_git_repo / "tasks"
        spec_path = _write_spec(
            tasks,
            slug="weather-skill",
            status="approved",
            whitelist_paths=[
                "src/skills/weather_skill/skill.py",
                "tasks/2026-04-26-weather-skill.yaml",
            ],
        )
        _git(tmp_git_repo, "add", str(spec_path.relative_to(tmp_git_repo)))
        _git(tmp_git_repo, "commit", "-m", "spec")

        skill = _make_skill(
            repo_root=tmp_git_repo,
            sdk_runner=_editor_writes_files(),
        )
        result = await skill.execute("/spec_run weather-skill", _ctx())
        assert result.success


# ---------------------------------------------------------------- prepare


class TestPrepare:
    async def test_prepare_returns_plan(self, tmp_git_repo: Path) -> None:
        skill = _make_skill(repo_root=tmp_git_repo)
        plan = await skill.prepare("/spec_run weather-skill", _ctx())
        assert plan.skill_name == "implement_spec"
        assert plan.skill_type == "delegated"
        assert plan.estimated_tokens > 0
