"""Editor prompt content tests (Phase 15 calibration).

The Editor's user prompt is the only context the SDK sees besides the
system prompt and the spec object. Two SpecModel fields were silently
dropped in Phase 13 — closing those holes here so the next live cycle
doesn't replay them.

Critical holes addressed:

* ``research_findings`` (KB #72 / #71) — Architect spends a budget on
  research before writing the spec. If those citations don't reach the
  Editor, it re-derives the same KB facts (or, worse, ignores them and
  reinvents the wheel).
* ``failed_attempts`` — populated by ``_mark_failed`` on every red
  cycle. On retry the Editor must see what already broke; otherwise it
  repeats the same path.

Tests reuse the ``_spec`` helper pattern from ``test_dry_run.py`` —
``SpecModel`` constructor, no fixture file required.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

import pytest

pytestmark = pytest.mark.contract


def _spec(**overrides: Any) -> Any:
    from src.skills.spec_command.parser import (
        FailingTest,
        SpecModel,
    )

    base: dict[str, Any] = {
        "slug": "weather-skill",
        "title": "Add weather skill",
        "created_at": datetime(2026, 4, 26, 12, 0, tzinfo=UTC),
        "created_by": "zhvusha",
        "tier": 1,
        "goal": (
            "Дать Жвуше команду /weather для admin_user_id. "
            "Проверка через failing test."
        ),
        "failing_test": FailingTest(
            file="tests/skills/weather/test_contract.py",
            name="test_returns_temp",
            spec="Mock API → response contains '12.5'.",
        ),
        "whitelist_paths": [
            "src/skills/weather/__init__.py",
            "src/skills/weather/skill.py",
            "tests/skills/weather/test_contract.py",
        ],
        "blast_radius": ["new skill, no existing skill touched"],
        "rollback_path": ["git revert", "rm -rf src/skills/weather/"],
        "preserve_behavior": [
            "Existing skills, fallbacks, tests and chat behaviour stay intact.",
        ],
        "allowed_simplifications": [],
        "rationale": "Spec is generated by Жвуша and needs archive evidence.",
        "source_provenance": [
            {
                "url": "local:test",
                "source_type": "local_repo",
                "trust_tier": "direct",
                "claim": "Test helper generated this spec.",
            }
        ],
    }
    base.update(overrides)
    return SpecModel(**base)


# ---------------------------------------------------------------- research


class TestUserPromptResearchFindings:
    """``spec.research_findings`` must surface in the Editor user prompt.

    Otherwise the Architect's KB research is wasted — Editor doesn't see
    the cited entries and re-derives them (or ignores them).
    """

    def test_includes_each_finding_excerpt(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import ResearchFinding

        spec = _spec(
            research_findings=[
                ResearchFinding(
                    source="kb_71",
                    excerpt="Spec must contain failing test as objective",
                    relevance="motivates failing_test field",
                ),
                ResearchFinding(
                    source="kb_90",
                    excerpt="ANTHROPIC_API_KEY popped before SDK init",
                    relevance="auth via OAuth not API",
                ),
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "Spec must contain failing test as objective" in prompt
        assert "ANTHROPIC_API_KEY popped before SDK init" in prompt

    def test_includes_each_source_id(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import ResearchFinding

        spec = _spec(
            research_findings=[
                ResearchFinding(source="kb_71", excerpt="x", relevance="y"),
                ResearchFinding(source="kb_90", excerpt="a", relevance="b"),
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "kb_71" in prompt
        assert "kb_90" in prompt

    def test_includes_relevance_explanations(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import ResearchFinding

        spec = _spec(
            research_findings=[
                ResearchFinding(
                    source="kb_71",
                    excerpt="x",
                    relevance="motivates failing_test field",
                ),
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "motivates failing_test field" in prompt

    def test_omits_section_when_empty(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec()  # research_findings defaults to []
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        # No empty/garbage section header for a missing block.
        assert "research findings" not in prompt.lower()


# ---------------------------------------------------------------- attempts


class TestUserPromptFailedAttempts:
    """``spec.failed_attempts`` must surface on retry — otherwise Editor
    repeats the same path that already failed."""

    def test_includes_each_attempt_when_present(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec(
            failed_attempts=[
                "First: SDK returned non-YAML",
                "Second: caps gate hit before SDK ran",
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "First: SDK returned non-YAML" in prompt
        assert "Second: caps gate hit before SDK ran" in prompt

    def test_omits_section_when_empty(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec()  # failed_attempts defaults to []
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        # No empty heading like "Previous failed attempts" with nothing
        # under it.
        lower = prompt.lower()
        assert "previous failed attempt" not in lower
        assert "previous attempts" not in lower


class TestUserPromptArchivePreviousAttempts:
    """Archive lessons retrieved at spec time must reach the Editor."""

    def test_includes_archive_previous_attempts(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec(
            previous_attempts=[
                {
                    "archive_slug": "greeting-calibration-failed",
                    "status": "failed",
                    "tier": 2,
                    "insight": "Previous attempt flattened Жвуша's personality.",
                    "tests_summary": "prompt regression failed",
                }
            ]
        )

        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)

        assert "greeting-calibration-failed" in prompt
        assert "flattened Жвуша" in prompt


# ---------------------------------------------------------------- preserves


class TestUserPromptPreservesExistingFields:
    """Sanity: the calibration must not drop the fields that already
    worked — Phase 13 contract regressions show up here."""

    def test_includes_slug_title_tier(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec()
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "weather-skill" in prompt
        assert "Add weather skill" in prompt
        assert "Tier: 1" in prompt

    def test_includes_failing_test_coordinates(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec()
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "tests/skills/weather/test_contract.py" in prompt
        assert "test_returns_temp" in prompt

    def test_includes_whitelist_paths(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec()
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "src/skills/weather/skill.py" in prompt


class TestNoDowngradePromptContract:
    def test_user_prompt_includes_preserve_behavior(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec(
            preserve_behavior=[
                "Keep existing personal chat tone, fallbacks and safety gates.",
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "Preserve behaviour" in prompt
        assert "Keep existing personal chat tone" in prompt

    def test_user_prompt_states_no_allowed_simplifications_when_empty(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        prompt = ImplementSpecSkill._build_user_prompt(spec=_spec())
        assert "Allowed simplifications" in prompt
        assert "не разрешены" in prompt

    def test_user_prompt_includes_explicit_allowed_simplification(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec(
            allowed_simplifications=[
                "Remove duplicate legacy greeting example after preserving coverage.",
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "Remove duplicate legacy greeting example" in prompt

    def test_user_prompt_includes_chat_context(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec(
            chat_context=[
                "Никита: сначала хочу обсудить приветствие",
                "Жвуша: убираем театральность, но сохраняем живость.",
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "/код dialogue context" in prompt
        assert "сначала хочу обсудить" in prompt
        assert "сохраняем живость" in prompt

    def test_system_prompt_binds_no_downgrade_principle(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        prompt = ImplementSpecSkill._build_system_prompt().lower()
        assert "no-downgrade" in prompt
        assert "preserve_behavior" in prompt
        assert "allowed_simplifications" in prompt
        assert "stop" in prompt


# ----------------------------------------------------------- tdd invariants


class TestSystemPromptTddInvariants:
    """System prompt branches by ``spec.kind`` so the Editor knows
    whether existing tests can be touched.

    FEATURE / FIX / DOCS: existing tests are immutable; if the test
    can't go green by editing code in the whitelist, STOP.

    REFACTOR: existing tests may be updated *structurally* (renamed
    imports, renamed symbol references, updated call signatures) — but
    NEVER assertion logic / expected values.

    Tests live in ``whitelist_paths`` (Editor needs them in RED-phase to
    create new files), so neither the PreToolUse hook nor pre-commit
    catches a "fix" that flips an existing test's assertions to go
    green. The system prompt is the only soft barrier.
    """

    @pytest.mark.parametrize("kind_name", ["FEATURE", "FIX", "DOCS"])
    def test_test_immutable_kinds_forbid_modifying_existing_tests(
        self, kind_name: str
    ) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        kind = SpecKind[kind_name]
        prompt = ImplementSpecSkill._build_system_prompt(kind=kind).lower()
        assert "existing test" in prompt or "existing tests" in prompt
        assert any(
            phrase in prompt
            for phrase in (
                "never modify",
                "do not modify",
                "don't modify",
                "never edit existing test",
            )
        )

    @pytest.mark.parametrize("kind_name", ["FEATURE", "FIX", "DOCS"])
    def test_test_immutable_kinds_direct_to_fix_code(self, kind_name: str) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        kind = SpecKind[kind_name]
        prompt = ImplementSpecSkill._build_system_prompt(kind=kind).lower()
        assert "fix the code" in prompt or "fix code, not the test" in prompt

    def test_refactor_kind_allows_structural_test_edits(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        prompt = ImplementSpecSkill._build_system_prompt(kind=SpecKind.REFACTOR).lower()
        # Allows structural updates to existing tests.
        assert any(
            term in prompt
            for term in ("renamed import", "renamed symbol", "structural")
        )

    def test_refactor_kind_still_forbids_assertion_edits(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        prompt = ImplementSpecSkill._build_system_prompt(kind=SpecKind.REFACTOR).lower()
        # Even in refactor mode, assertion logic is still off-limits.
        assert "assertion" in prompt
        assert any(
            phrase in prompt
            for phrase in ("never", "do not", "don't", "must not", "forbid")
        )

    def test_default_call_uses_feature_kind(self) -> None:
        """Backwards-compat: ``_build_system_prompt()`` without args
        defaults to the strictest kind (FEATURE)."""
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        default = ImplementSpecSkill._build_system_prompt()
        feature = ImplementSpecSkill._build_system_prompt(kind=SpecKind.FEATURE)
        assert default == feature


class TestUserPromptIncludesKind:
    """User prompt must surface ``spec.kind`` so the Editor sees the
    same classification the system prompt branches on."""

    def test_kind_value_present_for_refactor(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        spec = _spec(kind=SpecKind.REFACTOR)
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "refactor" in prompt.lower()

    def test_kind_value_present_for_feature(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        spec = _spec(kind=SpecKind.FEATURE)
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "feature" in prompt.lower()


# ------------------------------------------------- existing_tests_to_update


class TestSystemPromptExistingTestsToUpdate:
    """System prompt must teach the Editor that
    ``spec.existing_tests_to_update`` is the only legitimate channel for
    mutating an existing test, and even so only within the
    ``allowed_changes`` envelope.

    Phase 16 — Architect declares legitimate test mutations at spec
    time when the spec extends a finite collection behind a hidden
    contract test. Without this rule in the system prompt the Editor's
    blanket "existing tests are immutable" instruction collides with
    the spec's explicit list, producing either an unjustified refusal
    or a free-for-all rewrite. Both are wrong — the prompt must
    distinguish the two cases.

    The behaviour depends on whether the list is empty or non-empty,
    so ``_build_system_prompt`` must take it as an argument.
    """

    @pytest.mark.parametrize("kind_name", ["FEATURE", "FIX", "DOCS"])
    def test_empty_list_keeps_existing_tests_immutable(self, kind_name: str) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        kind = SpecKind[kind_name]
        prompt = ImplementSpecSkill._build_system_prompt(
            kind=kind, existing_tests_to_update=[]
        ).lower()
        # Empty list ⇒ all existing tests immutable, same as pre-Phase-16.
        assert "existing test" in prompt
        assert any(
            phrase in prompt
            for phrase in ("never modify", "do not modify", "don't modify")
        )

    @pytest.mark.parametrize("kind_name", ["FEATURE", "FIX", "DOCS"])
    def test_nonempty_list_softens_to_only_listed_tests(self, kind_name: str) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import (
            ExistingTestUpdate,
            SpecKind,
        )

        kind = SpecKind[kind_name]
        prompt = ImplementSpecSkill._build_system_prompt(
            kind=kind,
            existing_tests_to_update=[
                ExistingTestUpdate(
                    path="tests/research/test_research_service.py",
                    test_name="TestResearchPresets.test_four_presets_defined",
                    reason="adding bug_investigation breaks fixed-set assertion",
                    allowed_changes="add 'bug_investigation' to the asserted set",
                )
            ],
        ).lower()
        # Must reference the channel by name.
        assert "existing_tests_to_update" in prompt
        # Must explicitly say outside-the-list is still forbidden — the
        # softening is *exception-only*, not a reset of the rule.
        assert any(
            phrase in prompt
            for phrase in (
                "outside this list",
                "not in this list",
                "outside the list",
                "any test not in",
                "tests not listed",
                "any other existing test",
            )
        )

    def test_nonempty_list_includes_each_path(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import (
            ExistingTestUpdate,
            SpecKind,
        )

        prompt = ImplementSpecSkill._build_system_prompt(
            kind=SpecKind.FEATURE,
            existing_tests_to_update=[
                ExistingTestUpdate(
                    path="tests/research/test_research_service.py",
                    test_name="TestResearchPresets.test_four_presets_defined",
                    reason="extends PRESETS",
                    allowed_changes="add the new entry",
                ),
                ExistingTestUpdate(
                    path="tests/skills/research/test_presets.py",
                    test_name="test_baseline_count",
                    reason="extends PRESETS",
                    allowed_changes="bump expected count by 1",
                ),
            ],
        )
        assert "tests/research/test_research_service.py" in prompt
        assert "tests/skills/research/test_presets.py" in prompt

    def test_nonempty_list_includes_each_test_name(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import (
            ExistingTestUpdate,
            SpecKind,
        )

        prompt = ImplementSpecSkill._build_system_prompt(
            kind=SpecKind.FEATURE,
            existing_tests_to_update=[
                ExistingTestUpdate(
                    path="tests/research/test_research_service.py",
                    test_name="TestResearchPresets.test_four_presets_defined",
                    reason="extends PRESETS",
                    allowed_changes="add the new entry",
                )
            ],
        )
        assert "TestResearchPresets.test_four_presets_defined" in prompt

    def test_nonempty_list_includes_allowed_changes_envelope(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import (
            ExistingTestUpdate,
            SpecKind,
        )

        prompt = ImplementSpecSkill._build_system_prompt(
            kind=SpecKind.FEATURE,
            existing_tests_to_update=[
                ExistingTestUpdate(
                    path="tests/research/test_research_service.py",
                    test_name="TestResearchPresets.test_four_presets_defined",
                    reason="extends PRESETS",
                    allowed_changes="add 'bug_investigation' to the asserted set",
                )
            ],
        )
        # The envelope must travel into the prompt verbatim — Editor uses it
        # as the contract for what it may do.
        assert (
            "add 'bug_investigation' to the asserted set" in prompt
            or 'add "bug_investigation" to the asserted set' in prompt
        )

    def test_default_call_omits_existing_tests_to_update(self) -> None:
        """Backward-compat: existing callers (and tests for old
        behaviour) pass no kwarg and get the empty-list semantics."""
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import SpecKind

        default = ImplementSpecSkill._build_system_prompt(kind=SpecKind.FEATURE)
        empty = ImplementSpecSkill._build_system_prompt(
            kind=SpecKind.FEATURE, existing_tests_to_update=[]
        )
        assert default == empty


class TestUserPromptExistingTestsToUpdate:
    """User prompt must enumerate ``spec.existing_tests_to_update`` so
    the Editor sees the concrete entries (with reason + allowed_changes)
    alongside the rest of the spec context."""

    def test_includes_each_listed_test(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import ExistingTestUpdate

        spec = _spec(
            existing_tests_to_update=[
                ExistingTestUpdate(
                    path="tests/research/test_research_service.py",
                    test_name="TestResearchPresets.test_four_presets_defined",
                    reason="adding bug_investigation breaks fixed-set assertion",
                    allowed_changes="add 'bug_investigation' to the asserted set",
                )
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "tests/research/test_research_service.py" in prompt
        assert "TestResearchPresets.test_four_presets_defined" in prompt

    def test_includes_reason_and_allowed_changes(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill
        from src.skills.spec_command.parser import ExistingTestUpdate

        spec = _spec(
            existing_tests_to_update=[
                ExistingTestUpdate(
                    path="tests/research/test_research_service.py",
                    test_name="TestResearchPresets.test_four_presets_defined",
                    reason="adding bug_investigation breaks fixed-set assertion",
                    allowed_changes="add 'bug_investigation' to the asserted set",
                )
            ]
        )
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        assert "adding bug_investigation breaks fixed-set assertion" in prompt
        assert "add 'bug_investigation' to the asserted set" in prompt

    def test_omits_section_when_empty(self) -> None:
        from src.skills.implement_spec.skill import ImplementSpecSkill

        spec = _spec()  # default empty list
        prompt = ImplementSpecSkill._build_user_prompt(spec=spec)
        # No empty-block heading.
        lower = prompt.lower()
        assert "existing tests to update" not in lower
        assert "existing_tests_to_update" not in lower
