"""Contract tests for dry-run simulation (Phase 13).

Dry-run is what runs whenever ``SELF_CODING_ENABLED=False`` or when an
operator passes ``--dry-run``. The function must:

* Never touch ``git`` or the filesystem.
* Never call the SDK.
* Produce a human-readable plan referencing the spec slug, tier, and
  whitelist so Никита can sanity-check before flipping the flag.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

import pytest

pytestmark = pytest.mark.contract


def _spec(**overrides: Any) -> Any:
    from src.skills.spec_command.parser import (
        FailingTest,
        SpecModel,
    )

    base: dict[str, Any] = {
        "slug": "weather-skill",
        "title": "Add weather skill",
        "created_at": datetime(2026, 4, 26, 12, 0, tzinfo=UTC),
        "created_by": "zhvusha",
        "tier": 1,
        "goal": "Дать Жвуше команду /weather для admin_user_id.",
        "failing_test": FailingTest(
            file="tests/skills/weather/test_contract.py",
            name="test_returns_temp",
            spec="Mock API → response contains '12.5'.",
        ),
        "whitelist_paths": [
            "src/skills/weather/__init__.py",
            "src/skills/weather/skill.py",
            "tests/skills/weather/test_contract.py",
        ],
        "blast_radius": ["new skill, no existing skill touched"],
        "rollback_path": ["git revert", "rm -rf src/skills/weather/"],
        "preserve_behavior": [
            "Existing skills, fallbacks, tests and chat behaviour stay intact.",
        ],
        "allowed_simplifications": [],
        "rationale": "Spec is generated by Жвуша and needs archive evidence.",
        "source_provenance": [
            {
                "url": "local:test",
                "source_type": "local_repo",
                "trust_tier": "direct",
                "claim": "Test helper generated this spec.",
            }
        ],
    }
    base.update(overrides)
    return SpecModel(**base)


class TestSimulateOutput:
    def test_includes_slug(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())
        assert "weather-skill" in result.would_produce

    def test_includes_tier(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec(tier=2))
        assert "tier" in result.would_produce.lower() or "Tier" in result.would_produce
        assert "2" in result.would_produce

    def test_includes_whitelist_paths(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())
        assert "src/skills/weather/skill.py" in result.would_produce

    def test_includes_preserve_behavior_contract(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())
        assert "Preserve behaviour" in result.would_produce
        assert "Existing skills" in result.would_produce

    def test_includes_chat_context(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(
            spec=_spec(
                chat_context=[
                    "Никита: сначала обсудили приветствие",
                    "Жвуша: сохраняем живость без театра.",
                ]
            )
        )
        assert "/код dialogue context" in result.would_produce
        assert "сначала обсудили приветствие" in result.would_produce

    def test_includes_archive_previous_attempts(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(
            spec=_spec(
                previous_attempts=[
                    {
                        "archive_slug": "greeting-calibration-failed",
                        "status": "failed",
                        "tier": 2,
                        "insight": "Previous attempt missed personality context.",
                    }
                ]
            )
        )

        assert "archive previous attempts" in result.would_produce.lower()
        assert "greeting-calibration-failed" in result.would_produce

    def test_includes_temporary_worktree_isolation(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())
        assert "temporary detached git worktree" in result.would_produce
        assert "cherry-pick" in result.would_produce
        assert "zhvusha/weather-skill" not in result.would_produce

    def test_dependencies_available_true(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())
        assert result.dependencies_available is True

    def test_would_succeed_true_for_valid_spec(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())
        assert result.would_succeed is True

    def test_no_side_effects(self, tmp_path: Any) -> None:
        """Calling simulate must not create files / dirs."""
        from src.skills.implement_spec.dry_run import simulate

        before = list(tmp_path.iterdir())
        simulate(spec=_spec())
        after = list(tmp_path.iterdir())
        assert before == after


class TestSimulateExistingTestsToUpdate:
    """Phase 16: when ``spec.existing_tests_to_update`` is non-empty,
    the dry-run plan must surface each entry so Никита can sanity-check
    that legitimately-mutated tests are exactly the ones Architect
    intended.
    """

    def test_includes_each_listed_path(self) -> None:
        from src.skills.implement_spec.dry_run import simulate
        from src.skills.spec_command.parser import ExistingTestUpdate

        result = simulate(
            spec=_spec(
                existing_tests_to_update=[
                    ExistingTestUpdate(
                        path="tests/research/test_research_service.py",
                        test_name=("TestResearchPresets.test_four_presets_defined"),
                        reason=("adding bug_investigation breaks fixed-set assertion"),
                        allowed_changes=("add 'bug_investigation' to the asserted set"),
                    ),
                    ExistingTestUpdate(
                        path="tests/skills/research/test_presets.py",
                        test_name="test_baseline_count",
                        reason="extending PRESETS",
                        allowed_changes="bump expected count by 1",
                    ),
                ]
            )
        )
        assert "tests/research/test_research_service.py" in result.would_produce
        assert "tests/skills/research/test_presets.py" in result.would_produce

    def test_includes_test_name_and_envelope(self) -> None:
        from src.skills.implement_spec.dry_run import simulate
        from src.skills.spec_command.parser import ExistingTestUpdate

        result = simulate(
            spec=_spec(
                existing_tests_to_update=[
                    ExistingTestUpdate(
                        path="tests/research/test_research_service.py",
                        test_name=("TestResearchPresets.test_four_presets_defined"),
                        reason="adding new entry",
                        allowed_changes="add 'bug_investigation' to set",
                    )
                ]
            )
        )
        assert "TestResearchPresets.test_four_presets_defined" in result.would_produce
        assert "add 'bug_investigation' to set" in result.would_produce

    def test_omits_block_when_empty(self) -> None:
        from src.skills.implement_spec.dry_run import simulate

        result = simulate(spec=_spec())  # default empty
        assert "existing test" not in result.would_produce.lower()
        assert "existing_tests_to_update" not in result.would_produce
