"""Shared Agent Runtime foundation for ZHVUSHA.

The runtime is intentionally separate from ``chat_self_coding``.  ``/код`` can
be migrated onto it incrementally while the existing self-coding pipeline stays
available as a fallback.
"""

from src.agent_runtime.approvals import (
    AgentApprovalRequest,
    AgentToolApproval,
    AgentToolApprovalGrant,
    AgentToolApprovalGrantStore,
    FileAgentApprovalStore,
    FileAgentToolApprovalGrantStore,
    InMemoryAgentToolApprovalGrantStore,
)
from src.agent_runtime.bridge import (
    AgentRuntimeExplorerRunner,
    SelfCodingAgentRuntimeRunner,
)
from src.agent_runtime.browser_artifacts import (
    BrowserCapabilityStatus,
    DownloadedContent,
    ReadOnlyBrowserArtifactProvider,
    ReadOnlyBrowserGatewayBundle,
    build_readonly_browser_gateway_bundle,
    build_readonly_browser_tool_gateway,
)
from src.agent_runtime.budget_policy import (
    AgentBudgetPolicy,
    AgentRuntimeBudgetUsageRecorder,
    AutonomyResourceLimitProfile,
    AutonomyResourcePolicy,
    AutonomyResourcePolicyDecision,
    AutonomyResourceUsageSnapshot,
    BudgetDecisionType,
    BudgetJobKind,
    BudgetPolicyDecision,
    BudgetPreflightGate,
    BudgetRoute,
    BudgetUsageRecord,
    BudgetUsageSnapshot,
    FileBudgetUsageLedger,
)
from src.agent_runtime.builtin_tools import build_builtin_tool_gateway
from src.agent_runtime.computer_use import (
    ChromeDevToolsLiveBrowserAdapter,
    ComputerUseActionKind,
    ComputerUseActionRequest,
    ComputerUseActionResult,
    ComputerUseControlSnapshot,
    ComputerUseHardStopArtifactStore,
    ComputerUseTool,
    ComputerUseWorkerBackend,
    FileComputerUseControlStateStore,
    HyprlandDesktopComputerUseAdapter,
    IrreversibleActionDetector,
    LocalChromeDevToolsClient,
    ManagedChromeDevToolsClient,
    PlaywrightIsolatedBrowserAdapter,
    build_computer_use_tool_gateway,
)
from src.agent_runtime.context import ContextPackBuilder
from src.agent_runtime.desktop_control import (
    AllowlistedDesktopActionExecutor,
    AsyncFixedArgvDesktopCommandRunner,
    DesktopActionKind,
    DesktopActionPlan,
    DesktopActionRequest,
    DesktopActionResult,
    DesktopCommandRunner,
    DesktopControlAuditLog,
    DesktopControlAuditRecord,
    DesktopControlPolicy,
    DesktopControlTool,
    DesktopControlWorkerBackend,
    FileDesktopControlAuditLog,
    build_desktop_control_tool_gateway,
    parse_desktop_command_map_json,
)
from src.agent_runtime.models import (
    AgentDefinition,
    AgentEvent,
    AgentJob,
    AgentJobStatus,
    CapabilityDefinition,
    ContextCapsule,
    ContextPack,
    Finding,
    FindingStatus,
    InvocationProfile,
)
from src.agent_runtime.registry import AgentRegistry, CapabilityRegistry
from src.agent_runtime.rendering import (
    AgentResultRendererRegistry,
    build_builtin_result_renderer_registry,
    render_capsule_for_chat,
    render_capsule_for_job,
    render_job_status,
)
from src.agent_runtime.retrieval import (
    FileSourceAwareMemoryRecall,
    MemorySourceKind,
    RelevantFileFinder,
    SourceAwareMemoryRecall,
    SourceAwareMemoryRecallProvider,
    SourceAwareMemoryRecord,
    SourceAwareRecallHit,
    load_source_aware_staging_records,
)
from src.agent_runtime.routing import (
    AgentMessageIntent,
    AgentRoutingDecision,
    latest_active_job_for_chat,
    route_message_for_active_job,
)
from src.agent_runtime.runtime import AgentRuntime, AgentWorkerBackend
from src.agent_runtime.self_work_context import (
    SelfWorkContextCapsuleBuilder,
    SelfWorkContextSnapshot,
    SelfWorkMcpHealth,
    SelfWorkRuntimeSignal,
    sanitize_self_work_text,
)
from src.agent_runtime.telegram_inbound import (
    FilePersonalTelegramInboundEventStore,
    PersonalTelegramInboundEvent,
    PersonalTelegramInboundListener,
    PersonalTelegramInboundReadOnlyIngestor,
    TelethonPersonalTelegramInboundListener,
    build_personal_telegram_inbound_capsule,
    build_personal_telegram_inbound_listener_from_settings,
    render_personal_telegram_inbound_capsule_for_chat,
)
from src.agent_runtime.topic_signals import TopicClusterReadySignal
from src.agent_runtime.voice_gateway import (
    NormalizedVoiceMessage,
    VoiceGatewayNormalizer,
    VoiceInputEnvelope,
    VoiceOutputEnvelope,
    VoiceOutputRenderer,
    VoiceTranscript,
)
from src.agent_runtime.workers.agency import AgencyWorkerBackend
from src.agent_runtime.workers.browser_workflow import (
    BrowserWorkflowDraftWorkerBackend,
)
from src.agent_runtime.workers.external_skill import (
    ExternalSkillAgentWorker,
    ExternalSkillInvocationAdapter,
)
from src.agent_runtime.workers.source_compare import SourceCompareWorkerBackend
from src.agent_runtime.workers.web import WebResearchWorkerBackend

__all__ = [
    "AgencyWorkerBackend",
    "AgentApprovalRequest",
    "AgentBudgetPolicy",
    "AgentDefinition",
    "AgentEvent",
    "AgentJob",
    "AgentJobStatus",
    "AgentMessageIntent",
    "AgentRegistry",
    "AgentResultRendererRegistry",
    "AgentRoutingDecision",
    "AgentRuntime",
    "AgentRuntimeBudgetUsageRecorder",
    "AgentRuntimeExplorerRunner",
    "AgentToolApproval",
    "AgentToolApprovalGrant",
    "AgentToolApprovalGrantStore",
    "AgentWorkerBackend",
    "AllowlistedDesktopActionExecutor",
    "AsyncFixedArgvDesktopCommandRunner",
    "AutonomyResourceLimitProfile",
    "AutonomyResourcePolicy",
    "AutonomyResourcePolicyDecision",
    "AutonomyResourceUsageSnapshot",
    "BrowserCapabilityStatus",
    "BrowserWorkflowDraftWorkerBackend",
    "BudgetDecisionType",
    "BudgetJobKind",
    "BudgetPolicyDecision",
    "BudgetPreflightGate",
    "BudgetRoute",
    "BudgetUsageRecord",
    "BudgetUsageSnapshot",
    "CapabilityDefinition",
    "CapabilityRegistry",
    "ChromeDevToolsLiveBrowserAdapter",
    "ComputerUseActionKind",
    "ComputerUseActionRequest",
    "ComputerUseActionResult",
    "ComputerUseControlSnapshot",
    "ComputerUseHardStopArtifactStore",
    "ComputerUseTool",
    "ComputerUseWorkerBackend",
    "ContextCapsule",
    "ContextPack",
    "ContextPackBuilder",
    "DesktopActionKind",
    "DesktopActionPlan",
    "DesktopActionRequest",
    "DesktopActionResult",
    "DesktopCommandRunner",
    "DesktopControlAuditLog",
    "DesktopControlAuditRecord",
    "DesktopControlPolicy",
    "DesktopControlTool",
    "DesktopControlWorkerBackend",
    "DownloadedContent",
    "ExternalSkillAgentWorker",
    "ExternalSkillInvocationAdapter",
    "FileAgentApprovalStore",
    "FileAgentToolApprovalGrantStore",
    "FileBudgetUsageLedger",
    "FileComputerUseControlStateStore",
    "FileDesktopControlAuditLog",
    "FilePersonalTelegramInboundEventStore",
    "FileSourceAwareMemoryRecall",
    "Finding",
    "FindingStatus",
    "HyprlandDesktopComputerUseAdapter",
    "InMemoryAgentToolApprovalGrantStore",
    "InvocationProfile",
    "IrreversibleActionDetector",
    "LocalChromeDevToolsClient",
    "ManagedChromeDevToolsClient",
    "MemorySourceKind",
    "NormalizedVoiceMessage",
    "PersonalTelegramInboundEvent",
    "PersonalTelegramInboundListener",
    "PersonalTelegramInboundReadOnlyIngestor",
    "PlaywrightIsolatedBrowserAdapter",
    "ReadOnlyBrowserArtifactProvider",
    "ReadOnlyBrowserGatewayBundle",
    "RelevantFileFinder",
    "SelfCodingAgentRuntimeRunner",
    "SelfWorkContextCapsuleBuilder",
    "SelfWorkContextSnapshot",
    "SelfWorkMcpHealth",
    "SelfWorkRuntimeSignal",
    "SourceAwareMemoryRecall",
    "SourceAwareMemoryRecallProvider",
    "SourceAwareMemoryRecord",
    "SourceAwareRecallHit",
    "SourceCompareWorkerBackend",
    "TelethonPersonalTelegramInboundListener",
    "TopicClusterReadySignal",
    "VoiceGatewayNormalizer",
    "VoiceInputEnvelope",
    "VoiceOutputEnvelope",
    "VoiceOutputRenderer",
    "VoiceTranscript",
    "WebResearchWorkerBackend",
    "build_builtin_result_renderer_registry",
    "build_builtin_tool_gateway",
    "build_computer_use_tool_gateway",
    "build_desktop_control_tool_gateway",
    "build_personal_telegram_inbound_capsule",
    "build_personal_telegram_inbound_listener_from_settings",
    "build_readonly_browser_gateway_bundle",
    "build_readonly_browser_tool_gateway",
    "latest_active_job_for_chat",
    "load_source_aware_staging_records",
    "parse_desktop_command_map_json",
    "render_capsule_for_chat",
    "render_capsule_for_job",
    "render_job_status",
    "render_personal_telegram_inbound_capsule_for_chat",
    "route_message_for_active_job",
    "sanitize_self_work_text",
]
